module cga

// mesh_io: Wavefront OBJ read/write plus 4x4 (row-major) matrix helpers.
// (glTF/GLB lives in mesh_io_gltf.v.)
import os
import math
import strconv

// --- 4x4 row-major matrix helpers -------------------------------------------

pub fn mat4_identity() [16]f64 {
	return [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]!
}

pub fn mat4_mul(a [16]f64, b [16]f64) [16]f64 {
	mut r := [16]f64{}
	for i in 0 .. 4 {
		for j in 0 .. 4 {
			mut s := 0.0
			for k in 0 .. 4 {
				s += a[i * 4 + k] * b[k * 4 + j]
			}
			r[i * 4 + j] = s
		}
	}
	return r
}

// transform_point applies a row-major matrix to a point (w = 1).
pub fn transform_point(m [16]f64, p [3]f64) [3]f64 {
	return [m[0] * p[0] + m[1] * p[1] + m[2] * p[2] + m[3],
		m[4] * p[0] + m[5] * p[1] + m[6] * p[2] + m[7],
		m[8] * p[0] + m[9] * p[1] + m[10] * p[2] +
			m[11]]!
}

// from_trs builds a row-major matrix from glTF TRS (quaternion x,y,z,w).
pub fn from_trs(translation [3]f64, rotation [4]f64, scale [3]f64) [16]f64 {
	tx := translation[0]
	ty := translation[1]
	tz := translation[2]
	mut qx := rotation[0]
	mut qy := rotation[1]
	mut qz := rotation[2]
	mut qw := rotation[3]
	sx := scale[0]
	sy := scale[1]
	sz := scale[2]
	n := math.sqrt(qx * qx + qy * qy + qz * qz + qw * qw)
	if n < 1e-12 {
		qx, qy, qz, qw = 0.0, 0.0, 0.0, 1.0
	} else {
		qx /= n
		qy /= n
		qz /= n
		qw /= n
	}
	r00 := 1.0 - 2.0 * (qy * qy + qz * qz)
	r01 := 2.0 * (qx * qy - qz * qw)
	r02 := 2.0 * (qx * qz + qy * qw)
	r10 := 2.0 * (qx * qy + qz * qw)
	r11 := 1.0 - 2.0 * (qx * qx + qz * qz)
	r12 := 2.0 * (qy * qz - qx * qw)
	r20 := 2.0 * (qx * qz - qy * qw)
	r21 := 2.0 * (qy * qz + qx * qw)
	r22 := 1.0 - 2.0 * (qx * qx + qy * qy)
	return [r00 * sx, r01 * sy, r02 * sz, tx, r10 * sx, r11 * sy, r12 * sz, ty, r20 * sx, r21 * sy,
		r22 * sz, tz, 0.0, 0.0, 0.0, 1.0]!
}

pub fn to_column_major(m [16]f64) [16]f64 {
	mut r := [16]f64{}
	for j in 0 .. 4 {
		for i in 0 .. 4 {
			r[j * 4 + i] = m[i * 4 + j]
		}
	}
	return r
}

pub fn from_column_major(vals [16]f64) [16]f64 {
	mut r := [16]f64{}
	for i in 0 .. 4 {
		for j in 0 .. 4 {
			r[i * 4 + j] = vals[j * 4 + i]
		}
	}
	return r
}

// --- OBJ --------------------------------------------------------------------

// ObjMesh is one mesh entry for save_obj (transform bakes vertices to world).
pub struct ObjMesh {
pub:
	vertices      [][3]f64
	faces         [][3]int
	has_transform bool
	transform     [16]f64
}

fn resolve_obj_index(ref string, vertex_count int, lineno int) !int {
	if ref == '' {
		return error('line ${lineno}: empty face vertex reference')
	}
	raw := strconv.atoi(ref) or { return error('line ${lineno}: illegal vertex index "${ref}"') }
	if raw == 0 {
		return error('line ${lineno}: OBJ indices are 1-based, 0 not allowed')
	}
	idx := if raw < 0 { vertex_count + raw } else { raw - 1 }
	if idx < 0 || idx >= vertex_count {
		return error('line ${lineno}: vertex index ${raw} out of range (${vertex_count} vertices)')
	}
	return idx
}

// load_obj parses a Wavefront OBJ file (v / f lines only).
pub fn load_obj(path string) !([][3]f64, [][3]int) {
	text := os.read_file(path) or { return error('cannot read ${path}') }
	mut vertices := [][3]f64{}
	mut faces := [][3]int{}
	for lineno, raw_line in text.split_into_lines() {
		trimmed := raw_line.all_before('#').trim_space()
		if trimmed == '' {
			continue
		}
		parts := trimmed.split(' ')
		if parts.len == 0 {
			continue
		}
		keyword := parts[0]
		fields := parts[1..]
		if keyword == 'v' {
			if fields.len < 3 {
				return error('line ${lineno + 1}: v needs at least 3 coordinates')
			}
			x := strconv.atof64(fields[0]) or { return error('bad coordinate') }
			y := strconv.atof64(fields[1]) or { return error('bad coordinate') }
			z := strconv.atof64(fields[2]) or { return error('bad coordinate') }
			vertices << [x, y, z]!
		} else if keyword == 'f' {
			mut indices := []int{}
			for tok in fields {
				ref := tok.all_before('/')
				indices << resolve_obj_index(ref, vertices.len, lineno + 1)!
			}
			if indices.len < 3 {
				return error('line ${lineno + 1}: face with < 3 vertices')
			}
			for i in 1 .. indices.len - 1 {
				faces << [indices[0], indices[i], indices[i + 1]]!
			}
		}
	}
	return vertices, faces
}

// mesh_vertex_world bakes a vertex through the mesh transform (or returns it
// unchanged when no transform is set).
fn mesh_vertex_world(m ObjMesh, p [3]f64) [3]f64 {
	if m.has_transform {
		return transform_point(m.transform, p)
	}
	return p
}

// save_obj writes meshes to an OBJ file.
pub fn save_obj(path string, meshes []ObjMesh) {
	mut lines := ['# generated by cga.mesh_io']
	mut offset := 0
	for mi, m in meshes {
		lines << 'o mesh_${mi}'
		for p in m.vertices {
			q := mesh_vertex_world(m, p)
			lines << 'v ${q[0]:.9g} ${q[1]:.9g} ${q[2]:.9g}'
		}
		for f in m.faces {
			lines << 'f ${f[0] + 1 + offset} ${f[1] + 1 + offset} ${f[2] + 1 + offset}'
		}
		offset += m.vertices.len
	}
	os.write_file(path, lines.join('\n') + '\n') or { panic('cannot write ${path}') }
}
