module cga

// 5D Conformal Geometric Algebra (CGA) multivector representation.
//
// A multivector has 32 components organised by grade:
//   grade 0: 1 scalar
//   grade 1: 5 vectors  {e1, e2, e3, e0, einf}
//   grade 2: 10 bivectors
//   grade 3: 10 trivectors
//   grade 4: 5 quadvectors
//   grade 5: 1 pseudoscalar
//
// The basis is the null basis {e1, e2, e3, e0, einf}: e0^2 = einf^2 = 0 and
// e0.einf = -1.  Component slot 4 is the e0 coefficient, slot 5 the einf
// coefficient, so the conformal weight of a point is stored explicitly (no
// basis-change cancellation at far origins).
//
// Unlike the Python reference (which stores components in MLX arrays), the V
// port stores the 32 coefficients in a plain fixed `[32]f64` array and performs
// the algebra on the CPU in full double precision.  The geometric-product table
// is the exact same table as `cga/multivector.py`, generated by
// `gen/gen_tables.py` into `multivector_tables.v`.  The render kernel is
// float32, exactly as in the reference.
import math

pub struct Multivector {
pub mut:
	values [32]f64
}

// --- constructors -----------------------------------------------------------

// mv_zero returns the zero multivector.
pub fn mv_zero() Multivector {
	return Multivector{}
}

// mv_scalar returns a scalar multivector (only the grade-0 component).
pub fn mv_scalar(s f64) Multivector {
	mut m := Multivector{}
	m.values[0] = s
	return m
}

// mv_vector builds a vector from euclidean components (v1,v2,v3) plus the
// e0/einf coefficients (v0/ve).
pub fn mv_vector(v1 f64, v2 f64, v3 f64, v0 f64, ve f64) Multivector {
	mut m := Multivector{}
	m.values[1] = v1
	m.values[2] = v2
	m.values[3] = v3
	m.values[4] = v0
	m.values[5] = ve
	return m
}

// mv_bivector builds a bivector from 10 grade-2 components in canonical order.
pub fn mv_bivector(components [10]f64) Multivector {
	mut m := Multivector{}
	for i in 0 .. 10 {
		m.values[grade_indices[grade_start[2] + i]] = components[i]
	}
	return m
}

// Basis vectors (grade-1).  Fresh values per call; the coefficients are exact.
pub fn e1() Multivector {
	return mv_vector(1.0, 0.0, 0.0, 0.0, 0.0)
}

pub fn e2() Multivector {
	return mv_vector(0.0, 1.0, 0.0, 0.0, 0.0)
}

pub fn e3() Multivector {
	return mv_vector(0.0, 0.0, 1.0, 0.0, 0.0)
}

pub fn e0() Multivector {
	return mv_vector(0.0, 0.0, 0.0, 1.0, 0.0)
}

pub fn einf() Multivector {
	return mv_vector(0.0, 0.0, 0.0, 0.0, 1.0)
}

// --- component access -------------------------------------------------------

// grade returns the grade-g projection.
pub fn (m Multivector) grade(g int) Multivector {
	mut res := Multivector{}
	for k := grade_start[g]; k < grade_start[g + 1]; k++ {
		res.values[grade_indices[k]] = m.values[grade_indices[k]]
	}
	return res
}

// scalar_part returns the grade-0 component.
pub fn (m Multivector) scalar_part() f64 {
	return m.values[0]
}

// vector_part returns the 5 grade-1 components.
pub fn (m Multivector) vector_part() [5]f64 {
	return [m.values[1], m.values[2], m.values[3], m.values[4], m.values[5]]!
}

// euclidean_vector returns the e1/e2/e3 coefficients.
pub fn (m Multivector) euclidean_vector() [3]f64 {
	return [m.values[1], m.values[2], m.values[3]]!
}

// e0_coeff returns the e0 (origin) coefficient — the conformal weight.
pub fn (m Multivector) e0_coeff() f64 {
	return m.values[4]
}

// einf_coeff returns the einf (point at infinity) coefficient.
pub fn (m Multivector) einf_coeff() f64 {
	return m.values[5]
}

// bivector_part returns the 10 grade-2 components.
pub fn (m Multivector) bivector_part() [10]f64 {
	mut out := [10]f64{}
	for i in 0 .. 10 {
		out[i] = m.values[grade_indices[grade_start[2] + i]]
	}
	return out
}

// coords returns the weight-normalised euclidean coordinates of a conformal
// point (x, y, z) = (v1, v2, v3) / e0_coeff.
pub fn (m Multivector) coords() [3]f64 {
	w := m.values[4]
	if math.abs(w) < 1e-12 {
		panic('multivector has no e0 component; not a finite point')
	}
	return [m.values[1] / w, m.values[2] / w, m.values[3] / w]!
}

// is_zero reports whether all components are approximately zero.
// (This is not CGA nullity — a conformal point is a null vector but not zero.)
pub fn (m Multivector) is_zero() bool {
	for v in m.values {
		if math.abs(v) > 1e-10 {
			return false
		}
	}
	return true
}

// vmax returns the maximum absolute component.
pub fn (m Multivector) vmax() f64 {
	mut mx := 0.0
	for v in m.values {
		a := math.abs(v)
		if a > mx {
			mx = a
		}
	}
	return mx
}

// --- operators --------------------------------------------------------------

pub fn (m Multivector) add(o Multivector) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] + o.values[i]
	}
	return res
}

pub fn (m Multivector) sub(o Multivector) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] - o.values[i]
	}
	return res
}

pub fn (m Multivector) mul_scalar(s f64) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] * s
	}
	return res
}

pub fn (m Multivector) div_scalar(s f64) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] / s
	}
	return res
}

pub fn (m Multivector) neg() Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = -m.values[i]
	}
	return res
}

// eq performs approximate equality (allclose, atol=1e-6).
pub fn (m Multivector) eq(o Multivector) bool {
	for i in 0 .. num_components {
		if math.abs(m.values[i] - o.values[i]) > 1e-6 {
			return false
		}
	}
	return true
}

// copy returns a fresh multivector with the same components.
pub fn (m Multivector) copy() Multivector {
	return m
}

// str renders non-zero components by grade.
pub fn (m Multivector) str() string {
	mut parts := []string{}
	for g in 0 .. num_grades {
		for k := grade_start[g]; k < grade_start[g + 1]; k++ {
			idx := grade_indices[k]
			v := m.values[idx]
			if math.abs(v) <= 1e-10 {
				continue
			}
			name := basis_names[idx]
			if name == '1' {
				parts << '${v:.4f}'
			} else {
				parts << '${v:+.4f}*${name}'
			}
		}
	}
	if parts.len == 0 {
		return 'Multivector(0)'
	}
	return 'Multivector(${parts.join(' ')})'
}

// --- algebra ----------------------------------------------------------------

// gp computes the geometric product using the precomputed sparse table.
pub fn (m Multivector) gp(o Multivector) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		a := m.values[i]
		if a == 0.0 {
			continue
		}
		for k := gp_row_start[i]; k < gp_row_start[i + 1]; k++ {
			b := o.values[gp_j[k]]
			if b == 0.0 {
				continue
			}
			res.values[gp_dst[k]] += gp_sign[k] * a * b
		}
	}
	return res
}

// ip computes the fat-dot inner product (Hestenes), matching clifford's `|`.
//
// A|B = sum_{r,s>=1} < <A>_r * <B>_s >_|r-s| ; scalar (grade-0) terms are zero.
pub fn (m Multivector) ip(o Multivector) Multivector {
	mut res := Multivector{}
	for ga in 1 .. num_grades {
		a_g := m.grade(ga)
		if a_g.is_zero() {
			continue
		}
		for gb in 1 .. num_grades {
			b_g := o.grade(gb)
			if b_g.is_zero() {
				continue
			}
			prod := a_g.gp(b_g)
			res = res.add(prod.grade(int(math.abs(f64(gb - ga)))))
		}
	}
	return res
}

// op computes the outer product.
//
// a ^ b = sum_{r,s} < <a>_r * <b>_s >_{r+s}
pub fn (m Multivector) op(o Multivector) Multivector {
	mut res := Multivector{}
	for ga in 0 .. num_grades {
		a_g := m.grade(ga)
		if a_g.is_zero() {
			continue
		}
		for gb in 0 .. num_grades - ga {
			b_g := o.grade(gb)
			if b_g.is_zero() {
				continue
			}
			prod := a_g.gp(b_g)
			res = res.add(prod.grade(ga + gb))
		}
	}
	return res
}

// reverse applies the reversal involution: grade-k blade * (-1)^(k(k-1)/2).
pub fn (m Multivector) reverse() Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] * reverse_mask[i]
	}
	return res
}

// grade_involution flips the sign of odd-grade components.
pub fn (m Multivector) grade_involution() Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] * involution_mask[i]
	}
	return res
}

// conjugate is the Clifford conjugate (reverse + grade involution).
pub fn (m Multivector) conjugate() Multivector {
	return m.reverse().grade_involution()
}

// dual is the Hodge dual: multiply by I^-1 = -blade31.  On this null basis
// the pseudoscalar I = e1e2e3e0einf squares to -1, so I^-1 = -I.
pub fn (m Multivector) dual() Multivector {
	mut i_inv := Multivector{}
	i_inv.values[31] = -1.0
	return m.gp(i_inv)
}

// undual inverts dual (dual(dual(x)) = -x, so undual = -dual).
pub fn (m Multivector) undual() Multivector {
	return m.dual().neg()
}

// meet returns the regressive product (self* ^ o*)* — the geometric
// intersection of two blades.  When the duals wedge to zero (contained or
// parallel blades) it falls back to the linear intersection of the two blade
// subspaces, which is exact for direct-form blades (CGA points/lines/planes
// and any purely linear blade) and returns the contained blade, e.g.
// meet(e12, e13) = e1 and meet(e12, e23) = e2.  Non-blade inputs panic.
pub fn (m Multivector) meet(o Multivector) Multivector {
	if m.is_zero() || o.is_zero() {
		return mv_zero()
	}
	ga := m.blade_grade()
	gb := o.blade_grade()
	if ga < 0 || gb < 0 {
		panic('meet: arguments must be blades')
	}
	if ga == 0 || gb == 0 {
		return mv_zero()
	}
	w := m.dual().op(o.dual())
	if !w.is_zero() {
		return w.dual()
	}
	// The duals share a factor: intersection of the linear spans.
	na := nullspace(rows_of_mask(blade_mask(m)))
	nb := nullspace(rows_of_mask(blade_mask(o)))
	mut merged := [][]f64{}
	for r in na {
		merged << r
	}
	for r in nb {
		merged << r
	}
	c := nullspace(merged)
	if c.len == 0 {
		return mv_zero()
	}
	return wedge_rows(c)
}

// join returns the smallest blade spanning both self and o: the union of
// their blade subspaces.  Non-blade inputs panic; scalar or zero inputs join
// as the other blade.
pub fn (m Multivector) join(o Multivector) Multivector {
	if m.is_zero() {
		return o
	}
	if o.is_zero() {
		return m
	}
	ga := m.blade_grade()
	gb := o.blade_grade()
	if ga < 0 || gb < 0 {
		panic('join: arguments must be blades')
	}
	if ga == 0 {
		return o
	}
	if gb == 0 {
		return m
	}
	mut rows := rows_of_mask(blade_mask(m))
	for r in rows_of_mask(blade_mask(o)) {
		rows << r
	}
	return wedge_rows(row_basis(rows))
}

// norm returns the euclidean norm sqrt(|<self.reverse(self)>_0|).
pub fn (m Multivector) norm() f64 {
	s := m.gp(m.reverse()).values[0]
	return math.sqrt(math.abs(s))
}

// normalized returns the unit-norm multivector (or zero if degenerate).
pub fn (m Multivector) normalized() Multivector {
	n := m.norm()
	if n < 1e-12 {
		return mv_zero()
	}
	return m.div_scalar(n)
}

// bulk returns the euclidean part (components without e0/einf).
pub fn (m Multivector) bulk() Multivector {
	mut res := Multivector{}
	for idx in [0, 1, 2, 3, 6, 7, 10, 16] {
		res.values[idx] = m.values[idx]
	}
	return res
}

// weight returns the conformal part (components containing e0/einf).
pub fn (m Multivector) weight() Multivector {
	return m.sub(m.bulk())
}

// --- blade ops (inverse, projections, contractions) --------------------------

// blade_grade returns the grade of a pure blade, or -1 when the multivector
// holds mixed grades or is zero.
fn (m Multivector) blade_grade() int {
	mut g := -1
	for i in 0 .. num_components {
		if m.values[i] != 0.0 {
			gi := bit_count(slot_mask[i])
			if g != -1 && gi != g {
				return -1
			}
			g = gi
		}
	}
	return g
}

// inverse returns A^-1 = rev(A)/(A rev(A))_0 for an invertible blade or
// versor; a general multivector with a non-scalar A*rev(A) panics.
pub fn (m Multivector) inverse() Multivector {
	prod := m.gp(m.reverse())
	s := prod.values[0]
	if math.abs(s) < 1e-12 || !prod.grade(0).eq(prod) {
		panic('inverse: only blades and versors with nonzero norm are supported')
	}
	return m.reverse().div_scalar(s)
}

// lc is the left contraction A _| B: sums of <_A_g _B_h>_(h-g) for g <= h.
pub fn (m Multivector) lc(o Multivector) Multivector {
	mut res := Multivector{}
	for ga in 1 .. num_grades {
		a_g := m.grade(ga)
		if a_g.is_zero() {
			continue
		}
		for gb in ga .. num_grades {
			b_g := o.grade(gb)
			if b_g.is_zero() {
				continue
			}
			res = res.add(a_g.gp(b_g).grade(gb - ga))
		}
	}
	return res
}

// rc is the right contraction A |_ B: sums of <_A_g _B_h>_(g-h) for g >= h.
pub fn (m Multivector) rc(o Multivector) Multivector {
	mut res := Multivector{}
	for ga in 1 .. num_grades {
		a_g := m.grade(ga)
		if a_g.is_zero() {
			continue
		}
		for gb in 1 .. ga + 1 {
			b_g := o.grade(gb)
			if b_g.is_zero() {
				continue
			}
			res = res.add(a_g.gp(b_g).grade(ga - gb))
		}
	}
	return res
}

// commutator returns [self, o] = (self o - o self) / 2.
pub fn (m Multivector) commutator(o Multivector) Multivector {
	return m.gp(o).sub(o.gp(m)).mul_scalar(0.5)
}

// anticommutator returns {self, o} = (self o + o self) / 2.
pub fn (m Multivector) anticommutator(o Multivector) Multivector {
	return m.gp(o).add(o.gp(m)).mul_scalar(0.5)
}

// proj projects self onto the blade o: (self . o) o^-1.
pub fn (m Multivector) proj(o Multivector) Multivector {
	return m.ip(o).gp(o.inverse())
}

// rej returns the part of self orthogonal to the blade o.
pub fn (m Multivector) rej(o Multivector) Multivector {
	return m.sub(m.proj(o))
}

// reflect mirrors self across the plane with the given normal: v' = -n v n
// with n the normalized normal; works for vectors and blades.
pub fn (m Multivector) reflect(normal [3]f64) Multivector {
	len2 := normal[0] * normal[0] + normal[1] * normal[1] + normal[2] * normal[2]
	if len2 < 1e-18 {
		panic('reflect: zero normal')
	}
	n := mv_vector(normal[0], normal[1], normal[2], 0.0, 0.0).div_scalar(math.sqrt(len2))
	return n.gp(m).gp(n).neg()
}

// --- subspace helpers for meet/join ------------------------------------------

// slot_mask maps a component slot to its generator bitmask (e1=1, e2=2,
// e3=4, e0=8, einf=16).  Slots are ordered lexicographically by generator,
// not by bitmask, so the mask must be looked up, never computed.
const slot_mask = [
	0,
	1,
	2,
	4,
	8,
	16, // grade 0-1
	3,
	5,
	9,
	17,
	6,
	10,
	18,
	12,
	20,
	24, // grade 2
	7,
	11,
	19,
	13,
	21,
	25,
	14,
	22,
	26,
	28, // grade 3
	15,
	23,
	27,
	29,
	30, // grade 4
	31, // grade 5
]

// bit_count counts set bits of a small non-negative integer.
fn bit_count(x int) int {
	mut n := 0
	mut v := x
	for v > 0 {
		n += v & 1
		v >>= 1
	}
	return n
}

// blade_mask returns the generator bitmask of a pure blade.
fn blade_mask(m Multivector) int {
	mut mask := 0
	for i in 0 .. num_components {
		if m.values[i] != 0.0 {
			mask |= slot_mask[i]
		}
	}
	return mask
}

// rows_of_mask returns the generator basis vectors of a blade mask as rows.
fn rows_of_mask(mask int) [][]f64 {
	mut rows := [][]f64{}
	for i in 0 .. 5 {
		if mask & (1 << i) != 0 {
			mut row := []f64{len: 5}
			row[i] = 1.0
			rows << row
		}
	}
	return rows
}

// row_basis reduces rows to RREF and returns the pivot rows, a basis of the
// row space.
fn row_basis(rows [][]f64) [][]f64 {
	mut mat := [][]f64{}
	for row in rows {
		mat << row.clone()
	}
	mut pivots := 0
	for col in 0 .. 5 {
		mut pivot := -1
		for i in pivots .. mat.len {
			if math.abs(mat[i][col]) > 1e-12 {
				pivot = i
				break
			}
		}
		if pivot < 0 {
			continue
		}
		tmp := mat[pivot]
		mat[pivot] = mat[pivots]
		mat[pivots] = tmp
		scale := mat[pivots][col]
		for c in col .. 5 {
			mat[pivots][c] = mat[pivots][c] / scale
		}
		for i in 0 .. mat.len {
			if i == pivots {
				continue
			}
			f := mat[i][col]
			if math.abs(f) < 1e-12 {
				continue
			}
			for c in col .. 5 {
				mat[i][c] = mat[i][c] - f * mat[pivots][c]
			}
		}
		pivots++
	}
	mut basis := [][]f64{}
	for i in 0 .. pivots {
		basis << mat[i]
	}
	return basis
}

// nullspace returns a basis of the solutions x of rows . x = 0, i.e. the
// orthogonal complement of the row space.
fn nullspace(rows [][]f64) [][]f64 {
	rref := row_basis(rows)
	mut pivot_cols := []int{}
	for row in rref {
		for c in 0 .. 5 {
			if math.abs(row[c]) > 1e-12 {
				pivot_cols << c
				break
			}
		}
	}
	mut basis := [][]f64{}
	for fc in 0 .. 5 {
		if pivot_cols.contains(fc) {
			continue
		}
		mut v := []f64{len: 5}
		v[fc] = 1.0
		for i, pc in pivot_cols {
			v[pc] = -rref[i][fc]
		}
		basis << v
	}
	return basis
}

// wedge_rows wedges the given independent 5D vectors in order.
fn wedge_rows(rows [][]f64) Multivector {
	mut res := mv_scalar(1.0)
	for row in rows {
		res = res.op(mv_vector(row[0], row[1], row[2], row[3], row[4]))
	}
	return res
}
