module cga

// 5D Conformal Geometric Algebra (CGA) multivector representation.
//
// A multivector has 32 components organised by grade:
//   grade 0: 1 scalar
//   grade 1: 5 vectors  {e1, e2, e3, e0, einf}
//   grade 2: 10 bivectors
//   grade 3: 10 trivectors
//   grade 4: 5 quadvectors
//   grade 5: 1 pseudoscalar
//
// The basis is the null basis {e1, e2, e3, e0, einf}: e0^2 = einf^2 = 0 and
// e0.einf = -1.  Component slot 4 is the e0 coefficient, slot 5 the einf
// coefficient, so the conformal weight of a point is stored explicitly (no
// basis-change cancellation at far origins).
//
// Unlike the Python reference (which stores components in MLX arrays), the V
// port stores the 32 coefficients in a plain fixed `[32]f64` array and performs
// the algebra on the CPU in full double precision.  The geometric-product table
// is the exact same table as `cga/multivector.py`, generated by
// `gen/gen_tables.py` into `multivector_tables.v`.
//
// `set_precision` is kept for API compatibility: the algebra core is always
// float64 here (the render kernel is float32, exactly as in the reference).

import math

pub struct Multivector {
pub mut:
	values [32]f64
}

// --- constructors -----------------------------------------------------------

// mv_zero returns the zero multivector.
pub fn mv_zero() Multivector {
	return Multivector{}
}

// mv_scalar returns a scalar multivector (only the grade-0 component).
pub fn mv_scalar(s f64) Multivector {
	mut m := Multivector{}
	m.values[0] = s
	return m
}

// mv_vector builds a vector from euclidean components (v1,v2,v3) plus the
// e0/einf coefficients (v0/ve).
pub fn mv_vector(v1 f64, v2 f64, v3 f64, v0 f64, ve f64) Multivector {
	mut m := Multivector{}
	m.values[1] = v1
	m.values[2] = v2
	m.values[3] = v3
	m.values[4] = v0
	m.values[5] = ve
	return m
}

// mv_bivector builds a bivector from 10 grade-2 components in canonical order.
pub fn mv_bivector(components [10]f64) Multivector {
	mut m := Multivector{}
	for i in 0 .. 10 {
		m.values[grade_indices[grade_start[2] + i]] = components[i]
	}
	return m
}

// Basis vectors (grade-1).  Fresh values per call; the coefficients are exact.
pub fn e1() Multivector {
	return mv_vector(1.0, 0.0, 0.0, 0.0, 0.0)
}

pub fn e2() Multivector {
	return mv_vector(0.0, 1.0, 0.0, 0.0, 0.0)
}

pub fn e3() Multivector {
	return mv_vector(0.0, 0.0, 1.0, 0.0, 0.0)
}

pub fn e0() Multivector {
	return mv_vector(0.0, 0.0, 0.0, 1.0, 0.0)
}

pub fn einf() Multivector {
	return mv_vector(0.0, 0.0, 0.0, 0.0, 1.0)
}

// --- component access -------------------------------------------------------

// grade returns the grade-g projection.
pub fn (m Multivector) grade(g int) Multivector {
	mut res := Multivector{}
	for k := grade_start[g]; k < grade_start[g + 1]; k++ {
		res.values[grade_indices[k]] = m.values[grade_indices[k]]
	}
	return res
}

// scalar_part returns the grade-0 component.
pub fn (m Multivector) scalar_part() f64 {
	return m.values[0]
}

// vector_part returns the 5 grade-1 components.
pub fn (m Multivector) vector_part() [5]f64 {
	return [m.values[1], m.values[2], m.values[3], m.values[4], m.values[5]]!
}

// euclidean_vector returns the e1/e2/e3 coefficients.
pub fn (m Multivector) euclidean_vector() [3]f64 {
	return [m.values[1], m.values[2], m.values[3]]!
}

// e0_coeff returns the e0 (origin) coefficient — the conformal weight.
pub fn (m Multivector) e0_coeff() f64 {
	return m.values[4]
}

// einf_coeff returns the einf (point at infinity) coefficient.
pub fn (m Multivector) einf_coeff() f64 {
	return m.values[5]
}

// bivector_part returns the 10 grade-2 components.
pub fn (m Multivector) bivector_part() [10]f64 {
	mut out := [10]f64{}
	for i in 0 .. 10 {
		out[i] = m.values[grade_indices[grade_start[2] + i]]
	}
	return out
}

// coords returns the weight-normalised euclidean coordinates of a conformal
// point (x, y, z) = (v1, v2, v3) / e0_coeff.
pub fn (m Multivector) coords() [3]f64 {
	w := m.values[4]
	if math.abs(w) < 1e-12 {
		panic('multivector has no e0 component; not a finite point')
	}
	return [m.values[1] / w, m.values[2] / w, m.values[3] / w]!
}

// is_zero reports whether all components are approximately zero.
// (This is not CGA nullity — a conformal point is a null vector but not zero.)
pub fn (m Multivector) is_zero() bool {
	for v in m.values {
		if math.abs(v) > 1e-10 {
			return false
		}
	}
	return true
}

// vmax returns the maximum absolute component.
pub fn (m Multivector) vmax() f64 {
	mut mx := 0.0
	for v in m.values {
		a := math.abs(v)
		if a > mx {
			mx = a
		}
	}
	return mx
}

// --- operators --------------------------------------------------------------

pub fn (m Multivector) add(o Multivector) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] + o.values[i]
	}
	return res
}

pub fn (m Multivector) sub(o Multivector) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] - o.values[i]
	}
	return res
}

pub fn (m Multivector) mul_scalar(s f64) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] * s
	}
	return res
}

pub fn (m Multivector) div_scalar(s f64) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] / s
	}
	return res
}

pub fn (m Multivector) neg() Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = -m.values[i]
	}
	return res
}

// eq performs approximate equality (allclose, atol=1e-6).
pub fn (m Multivector) eq(o Multivector) bool {
	for i in 0 .. num_components {
		if math.abs(m.values[i] - o.values[i]) > 1e-6 {
			return false
		}
	}
	return true
}

// copy returns a fresh multivector with the same components.
pub fn (m Multivector) copy() Multivector {
	return m
}

// str renders non-zero components by grade.
pub fn (m Multivector) str() string {
	mut parts := []string{}
	for g in 0 .. num_grades {
		for k := grade_start[g]; k < grade_start[g + 1]; k++ {
			idx := grade_indices[k]
			v := m.values[idx]
			if math.abs(v) <= 1e-10 {
				continue
			}
			name := basis_names[idx]
			if name == '1' {
				parts << '${v:.4f}'
			} else {
				parts << '${v:+.4f}*${name}'
			}
		}
	}
	if parts.len == 0 {
		return 'Multivector(0)'
	}
	return 'Multivector(${parts.join(' ')})'
}

// --- algebra ----------------------------------------------------------------

// gp computes the geometric product using the precomputed sparse table.
pub fn (m Multivector) gp(o Multivector) Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		a := m.values[i]
		if a == 0.0 {
			continue
		}
		for k := gp_row_start[i]; k < gp_row_start[i + 1]; k++ {
			b := o.values[gp_j[k]]
			if b == 0.0 {
				continue
			}
			res.values[gp_dst[k]] += gp_sign[k] * a * b
		}
	}
	return res
}

// ip computes the fat-dot inner product (Hestenes), matching clifford's `|`.
//
// A|B = sum_{r,s>=1} < <A>_r * <B>_s >_|r-s| ; scalar (grade-0) terms are zero.
pub fn (m Multivector) ip(o Multivector) Multivector {
	mut res := Multivector{}
	for ga in 1 .. num_grades {
		a_g := m.grade(ga)
		if a_g.is_zero() {
			continue
		}
		for gb in 1 .. num_grades {
			b_g := o.grade(gb)
			if b_g.is_zero() {
				continue
			}
			prod := a_g.gp(b_g)
			res = res.add(prod.grade(int(math.abs(f64(gb - ga)))))
		}
	}
	return res
}

// op computes the outer product.
//
// a ^ b = sum_{r,s} < <a>_r * <b>_s >_{r+s}
pub fn (m Multivector) op(o Multivector) Multivector {
	mut res := Multivector{}
	for ga in 0 .. num_grades {
		a_g := m.grade(ga)
		if a_g.is_zero() {
			continue
		}
		for gb in 0 .. num_grades - ga {
			b_g := o.grade(gb)
			if b_g.is_zero() {
				continue
			}
			prod := a_g.gp(b_g)
			res = res.add(prod.grade(ga + gb))
		}
	}
	return res
}

// reverse applies the reversal involution: grade-k blade * (-1)^(k(k-1)/2).
pub fn (m Multivector) reverse() Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] * reverse_mask[i]
	}
	return res
}

// grade_involution flips the sign of odd-grade components.
pub fn (m Multivector) grade_involution() Multivector {
	mut res := Multivector{}
	for i in 0 .. num_components {
		res.values[i] = m.values[i] * involution_mask[i]
	}
	return res
}

// conjugate is the Clifford conjugate (reverse + grade involution).
pub fn (m Multivector) conjugate() Multivector {
	return m.reverse().grade_involution()
}

// dual is the Hodge dual: multiply by I^-1 = +blade31 (I = e123^einf^e0).
pub fn (m Multivector) dual() Multivector {
	mut i_inv := Multivector{}
	i_inv.values[31] = 1.0
	return m.gp(i_inv)
}

// undual inverts dual (dual(dual(x)) = -x, so undual = -dual).
pub fn (m Multivector) undual() Multivector {
	return m.dual().neg()
}

// meet returns self v other = (self* ^ other*)* for two direct-form primitives.
pub fn (m Multivector) meet(o Multivector) Multivector {
	return m.dual().op(o.dual()).dual()
}

// norm returns the euclidean norm sqrt(|<self.reverse(self)>_0|).
pub fn (m Multivector) norm() f64 {
	s := m.gp(m.reverse()).values[0]
	return math.sqrt(math.abs(s))
}

// normalized returns the unit-norm multivector (or zero if degenerate).
pub fn (m Multivector) normalized() Multivector {
	n := m.norm()
	if n < 1e-12 {
		return mv_zero()
	}
	return m.div_scalar(n)
}

// bulk returns the euclidean part (components without e0/einf).
pub fn (m Multivector) bulk() Multivector {
	mut res := Multivector{}
	for idx in [0, 1, 2, 3, 6, 7, 10, 16] {
		res.values[idx] = m.values[idx]
	}
	return res
}

// weight returns the conformal part (components containing e0/einf).
pub fn (m Multivector) weight() Multivector {
	return m.sub(m.bulk())
}

// --- precision (compatibility shim) -----------------------------------------

// set_precision accepts "float32" or "float64" for API compatibility with the
// Python reference.  The V core is always float64 (double precision) on the
// CPU, so both modes are accepted and behave identically here.
pub fn set_precision(mode string) {
	if mode != 'float32' && mode != 'float64' {
		panic("precision must be 'float32' or 'float64', got '${mode}'")
	}
}
