pub mod flange_spec;
pub use self::flange_spec::*;
pub mod bolt_circle_spec;
pub use self::bolt_circle_spec::*;
pub mod gear_spec;
pub use self::gear_spec::*;
pub mod base_plate_spec;
pub use self::base_plate_spec::*;

pub fn fmt_num(x: f64) -> String {
    if x.is_finite() && x.fract() == 0.0 && x.abs() < 1e16 {
        format!("{x:.1}")
    } else {
        format!("{x}")
    }
}

fn fmt_v(v: [f64; 3]) -> String {
    format!("[{}, {}, {}]", fmt_num(v[0]), fmt_num(v[1]), fmt_num(v[2]))
}

pub fn gen_header(camera_pos: [f64; 3], camera_target: [f64; 3]) -> String {
    format!(
        "// generated by cgs_gen — do not hand-edit, regenerate from spec\n\
         background(color=0x2B3138);\n\
         camera(fov=45, position={}, target={});\n\
         directional_light(direction=[0.4, 1.0, 0.5], intensity=0.5);\n\
         point_light(position=[-5, 6, 4], intensity=0.55);\n\
         ambient_light(intensity=0.38);\n",
        fmt_v(camera_pos),
        fmt_v(camera_target)
    )
}

pub fn gen_post(r: f64, h: f64) -> String {
    format!(
        "rotate(axis=[1.0, 0.0, 0.0], angle=-1.5707963267948966) cylinder(r={}, h={});",
        fmt_num(r),
        fmt_num(h)
    )
}

pub fn gen_flange_assembly(
    flange: &FlangeSpec,
    bolts: &BoltCircleSpec,
    gear: &GearSpec,
    plate: &BasePlateSpec,
) -> String {
    let mut out = gen_header([7.5, 6.5, 9.5], [0.0, 1.8, 0.0]);
    out.push_str(&format!(
        "translate([0.0, 0.15, 0.0]) {{\n{}}}\n",
        plate.generate()
    ));
    out.push_str(&format!(
        "translate([0.0, 0.55, 0.0]) {{\n{}}}\n",
        flange.generate()
    ));
    out.push_str(&bolts.generate());
    out.push_str(&format!(
        "translate([0.0, 2.9, 0.0]) material(color=0x9BA1A6, roughness=0.3, metalness=0.8) {}\n",
        gen_post(0.55, 4.2)
    ));
    out.push_str(&format!(
        "translate([0.0, 1.25, 0.0]) material(color=0x9BA1A6, roughness=0.3, metalness=0.8) {}\n",
        gen_post(0.85, 0.9)
    ));
    out.push_str(&gear.generate());
    out.push_str(
        "translate([0.0, 4.45, 0.0]) rotate(axis=[1.0, 0.0, 0.0], angle=-1.5707963267948966) material(color=0x4A4F54, roughness=0.45, metalness=0.65) torus(R=0.72, r=0.16);\n\
         translate([0.0, 4.85, 0.0]) material(color=0x6E747A, roughness=0.4, metalness=0.7) box(s=[0.95, 0.5, 0.95]);\n\
         translate([0.62, 3.6, 0.0]) material(color=0xC8A24A, roughness=0.35, metalness=0.75) box(s=[0.18, 0.9, 0.18]);\n\
         material(color=0x3A4046, roughness=0.9) plane(n=[0.0, 1.0, 0.0], d=0.0);\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn post_golden() {
        assert_eq!(
            gen_post(2.6, 0.5),
            "rotate(axis=[1.0, 0.0, 0.0], angle=-1.5707963267948966) cylinder(r=2.6, h=0.5);"
        );
    }

    #[test]
    fn flange_has_all_holes_unrolled() {
        let s = FlangeSpec::default();
        let t = s.generate();
        assert!(t.contains("difference()"));

        assert_eq!(t.matches("cylinder(").count(), 10);
        assert!(t.contains("material(color=0x9BA1A6"));
    }

    #[test]
    fn generated_assembly_parses_and_counts() {
        let text = gen_flange_assembly(
            &FlangeSpec::default(),
            &BoltCircleSpec::default(),
            &GearSpec::default(),
            &BasePlateSpec::default(),
        );
        let (scene, _cam) = crate::cgs_load_result(&text, ".").expect("generated CGS must parse");

        assert_eq!(scene.objects.len(), 41);
    }

    #[test]
    fn gear_tooth_count() {
        let t = GearSpec::default().generate();
        assert_eq!(t.matches("box(s=").count(), 16);
    }
}
