pub mod flange_spec;
pub use self::flange_spec::*;
pub mod bolt_circle_spec;
pub use self::bolt_circle_spec::*;
pub mod gear_spec;
pub use self::gear_spec::*;
pub mod base_plate_spec;
pub use self::base_plate_spec::*;

pub fn fmt_num(x: f64) -> String {
    if x.is_finite() && x.fract() == 0.0 && x.abs() < 1e16 {
        format!("{x:.1}")
    } else {
        format!("{x}")
    }
}

fn fmt_v(v: [f64; 3]) -> String {
    format!("[{}, {}, {}]", fmt_num(v[0]), fmt_num(v[1]), fmt_num(v[2]))
}

/// JSX 场景骨架：背景/相机/灯光。子内容由各 spec 平铺填入。
pub fn gen_header(camera_pos: [f64; 3], camera_target: [f64; 3]) -> String {
    format!(
        "// generated by jsx_gen — do not hand-edit, regenerate from spec\n\
         export default (\n  <Scene background={{0x2B3138}}>\n    \
         <Camera fov={{45}} position={{ {} }} target={{ {} }} />\n    \
         <DirectionalLight direction={{[0.4, 1.0, 0.5]}} intensity={{0.5}} />\n    \
         <PointLight position={{[-5, 6, 4]}} intensity={{0.55}} />\n    \
         <AmbientLight intensity={{0.38}} />\n",
        fmt_v(camera_pos),
        fmt_v(camera_target)
    )
}

pub fn gen_footer() -> String {
    "  </Scene>\n);\n".to_string()
}

pub fn gen_post(r: f64, h: f64) -> String {
    format!(
        "<Rotate axis={{[1.0, 0.0, 0.0]}} angle={{ -1.5707963267948966 }}><Cylinder r={{ {} }} h={{ {} }} /></Rotate>",
        fmt_num(r),
        fmt_num(h)
    )
}

/// 结构化参数 → 平铺 JSX（无组件复用、确定性、可 diff、必然可解析）。
pub fn gen_flange_assembly(
    flange: &FlangeSpec,
    bolts: &BoltCircleSpec,
    gear: &GearSpec,
    plate: &BasePlateSpec,
) -> String {
    let mut out = gen_header([7.5, 6.5, 9.5], [0.0, 1.8, 0.0]);
    out.push_str(&format!(
        "    <Translate t={{[0.0, 0.15, 0.0]}}>\n{}    </Translate>\n",
        plate.generate()
    ));
    out.push_str(&format!(
        "    <Translate t={{[0.0, 0.55, 0.0]}}>\n{}    </Translate>\n",
        flange.generate()
    ));
    out.push_str(&bolts.generate());
    out.push_str(&format!(
        "    <Translate t={{[0.0, 2.9, 0.0]}}>{}</Translate>\n",
        gen_post_mat(0.55, 4.2, 0x9BA1A6, 0.3, 0.8)
    ));
    out.push_str(&format!(
        "    <Translate t={{[0.0, 1.25, 0.0]}}>{}</Translate>\n",
        gen_post_mat(0.85, 0.9, 0x9BA1A6, 0.3, 0.8)
    ));
    out.push_str(&gear.generate());
    out.push_str(&format!(
        "    <Translate t={{[0.0, 4.45, 0.0]}}><Rotate axis={{[1.0, 0.0, 0.0]}} angle={{ -1.5707963267948966 }}><Torus R={{0.72}} r={{0.16}} color={{0x4A4F54}} roughness={{0.45}} metalness={{0.65}} /></Rotate></Translate>\n\
         \x20   <Translate t={{[0.0, 4.85, 0.0]}}><Box s={{[0.95, 0.5, 0.95]}} color={{0x6E747A}} roughness={{0.4}} metalness={{0.7}} /></Translate>\n\
         \x20   <Translate t={{[0.62, 3.6, 0.0]}}><Box s={{[0.18, 0.9, 0.18]}} color={{0xC8A24A}} roughness={{0.35}} metalness={{0.75}} /></Translate>\n\
         \x20   <Plane n={{[0.0, 1.0, 0.0]}} d={{0.0}} color={{0x3A4046}} roughness={{0.9}} />\n",
    ));
    out.push_str(&gen_footer());
    out
}

pub fn gen_post_mat(r: f64, h: f64, color: u32, roughness: f64, metalness: f64) -> String {
    format!(
        "<Rotate axis={{[1.0, 0.0, 0.0]}} angle={{ -1.5707963267948966 }}><Cylinder r={{ {} }} h={{ {} }} color={{0x{:06X}}} roughness={{ {} }} metalness={{ {} }} /></Rotate>",
        fmt_num(r),
        fmt_num(h),
        color,
        fmt_num(roughness),
        fmt_num(metalness)
    )
}

/// 运动副全景（图模型版）：8 种副类型（revolute / continuous / prismatic / helical /
/// cylindrical / spherical / planar / fixed）各一个，外加两种高副——`<Gear>` 齿轮耦合
/// 与 `<Cam>` 凸轮接触。输出平铺 JSX（PascalCase 元素名），确定性、可 diff；
/// 场景报告里会逐条出现 `link` / `pair` / `gear` / `cam` / `anchor` 行。
///
/// 图模型（docs/kinematics-graph.md）：连杆是平铺的 `<Link>`，副是连杆之间的
/// 无向 `<Pair>`（约束是边，不是容器）；`<Anchor>` 选定世界固连体。
/// `revolute → <Gear> → prismatic` 与 `cam_driver → <Cam> → cam_follower` 显式排布。
pub fn gen_pairs_showcase() -> String {
    fn body(color: u32) -> String {
        format!(
            "<Box s={{[0.5,0.5,0.5]}} color={{0x{color:06X}}} roughness={{0.4}} metalness={{0.4}} />"
        )
    }
    fn pair_link(name: &str, kind: &str, x: f64, extra: &str, color: u32) -> String {
        format!(
            "    <Link name=\"{name}\">{}</Link>\n    <{tag} name=\"{name}\" a=\"base\" b=\"{name}\" at={{ {} }}{extra} />\n",
            body(color),
            fmt_v([x, 1.0, 0.0]),
            tag = match kind {
                "revolute" => "Revolute",
                "continuous" => "Continuous",
                "prismatic" => "Prismatic",
                "helical" => "Helical",
                "cylindrical" => "Cylindrical",
                "spherical" => "Spherical",
                "planar" => "Planar",
                _ => "Fixed",
            },
        )
    }
    let mut out = gen_header([7.0, 5.0, 10.0], [0.0, 1.0, 0.0]);
    out.push_str("    <Link name=\"base\" />\n    <Anchor link=\"base\" />\n");
    // 低副一排（y=1），x 从 -4 到 3。revolute 同时充当齿轮耦合的驱动侧。
    out.push_str(&pair_link(
        "revolute",
        "revolute",
        -4.0,
        " axis={[0,0,1]} q={0.6}",
        0xC0392B,
    ));
    out.push_str("    <Gear a=\"revolute\" b=\"prismatic\" ratio={0.5} />\n");
    out.push_str(&pair_link(
        "prismatic",
        "prismatic",
        -3.0,
        " axis={[0,1,0]} limit={[-1,1]}",
        0xF1C40F,
    ));
    out.push_str(&pair_link(
        "continuous",
        "continuous",
        -2.0,
        " axis={[0,0,1]}",
        0xE67E22,
    ));
    out.push_str(&pair_link(
        "helical",
        "helical",
        -1.0,
        " axis={[0,0,1]} pitch={0.3} q={0.5}",
        0x2ECC71,
    ));
    out.push_str(&pair_link(
        "cylindrical",
        "cylindrical",
        0.0,
        " axis={[0,0,1]} q={[0.4,0.2]}",
        0x1ABC9C,
    ));
    out.push_str(&pair_link(
        "spherical",
        "spherical",
        1.0,
        " q={[0.2,0.3,0.1]}",
        0x3498DB,
    ));
    out.push_str(&pair_link(
        "planar",
        "planar",
        2.0,
        " axis={[0,0,1]} q={[0.2,0.1,0.3]}",
        0x9B59B6,
    ));
    out.push_str(&pair_link("fixed", "fixed", 3.0, "", 0x95A5A6));
    // 高副：凸轮接触。驱动侧 = 偏心圆盘（revolute），从动侧 = 滚子推杆（prismatic）。
    // 限位只框住两支接触解中的一支，保证 cam_solve 的"唯一接触"成立。
    out.push_str(&format!(
        "    <Link name=\"cam_driver_link\"><Cylinder r={{0.4}} h={{0.2}} /></Link>\n    <Revolute name=\"cam_driver\" a=\"base\" b=\"cam_driver_link\" axis={{[0,0,1]}} at={{ {} }} q={{0.3}} />\n",
        fmt_v([0.0, 3.0, 0.0])
    ));
    out.push_str(
        "    <Cam a=\"cam_driver_link\" b=\"cam_follower_link\" \
         aProfile={{kind:\"circle\", c:[0.12,0,0], n:[0,0,1], r:0.4}} \
         bProfile={{kind:\"circle\", c:[0,0,0], n:[0,0,1], r:0.12}} />\n",
    );
    out.push_str(&format!(
        "    <Link name=\"cam_follower_link\"><Sphere r={{0.12}} /></Link>\n    <Prismatic name=\"cam_follower\" a=\"base\" b=\"cam_follower_link\" axis={{[1,0,0]}} at={{ {} }} limit={{[-0.4,-0.1]}} />\n",
        fmt_v([0.9, 3.0, 0.0])
    ));
    out.push_str("    <Plane n={[0,1,0]} d={0} color={0x3A4046} roughness={0.9} />\n");
    out.push_str(&gen_footer());
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn post_golden() {
        assert_eq!(
            gen_post(2.6, 0.5),
            "<Rotate axis={[1.0, 0.0, 0.0]} angle={ -1.5707963267948966 }><Cylinder r={ 2.6 } h={ 0.5 } /></Rotate>"
        );
    }

    #[test]
    fn flange_has_all_holes_unrolled() {
        let s = FlangeSpec::default();
        let t = s.generate();
        assert!(t.contains("<Difference"));
        assert_eq!(t.matches("<Cylinder").count(), 10);
        assert!(t.contains("color={0x9BA1A6}"));
    }

    #[test]
    fn generated_assembly_parses_and_counts() {
        let text = gen_flange_assembly(
            &FlangeSpec::default(),
            &BoltCircleSpec::default(),
            &GearSpec::default(),
            &BasePlateSpec::default(),
        );
        let run = crate::jsx::run_jsx(&text, None, ".").expect("generated JSX must run");
        assert_eq!(run.scene.objects.len(), 41);
    }

    #[test]
    fn gear_tooth_count() {
        let t = GearSpec::default().generate();
        assert_eq!(t.matches("<Box s=").count(), 16);
    }

    #[test]
    fn pairs_showcase_has_all_pairs() {
        let text = gen_pairs_showcase();
        let run = crate::jsx::run_jsx(&text, None, ".").expect("pairs showcase must run");
        let k = &run.kinematics;
        assert_eq!(k.pairs.len(), 10, "8 种副 + cam driver/follower");
        assert_eq!(k.gears.len(), 1, "1 个齿轮耦合（高副）");
        assert_eq!(k.cams.len(), 1, "1 个凸轮接触（高副）");
        assert_eq!(k.anchor.as_deref(), Some("base"));
        let kinds: Vec<&str> = k.pairs.iter().map(|p| p.kind.name()).collect();
        let all = [
            "revolute",
            "continuous",
            "prismatic",
            "helical",
            "cylindrical",
            "spherical",
            "planar",
            "fixed",
        ];
        for t in all {
            assert!(kinds.contains(&t), "缺少副类型 {t}: {kinds:?}");
        }
        // gear 推导：prismatic = 0.5·0.6 = 0.3
        let pri = k
            .pairs
            .iter()
            .find(|p| p.name.as_deref() == Some("prismatic"))
            .unwrap();
        assert!((pri.q[0] - 0.3).abs() < 1e-12, "gear 推导: {}", pri.q[0]);
        let rep = crate::scene_report::scene_report(
            &run.scene,
            &run.camera,
            &run.tags,
            k,
            &run.mass_props,
        );
        for t in all {
            assert!(rep.contains(&format!("type={t}")), "报告缺少 type={t}");
        }
        assert!(rep.contains("gear 0 a=\"revolute\""), "报告缺 gear 行");
        assert!(rep.contains("cam 0 a=\"cam_driver_link\""), "报告缺 cam 行");
        assert!(rep.contains("anchor \"base\""), "报告缺 anchor 行");
    }
}
