//! CGS text generation: structured params -> CGS source (the LLM codegen target).
//!
//! Mirrors `examples/cgs/mechanical.cgs` statement-for-statement. Output is
//! intentionally flat + unrolled (no `for` loops): deterministic, diffable,
//! and parseable by [`crate::cgs_load_result`] (roundtrip-tested below).

/// Format like the CGS parser's own `fmt_f64`: integers print as `N.0`.
pub fn fmt_num(x: f64) -> String {
    if x.is_finite() && x.fract() == 0.0 && x.abs() < 1e16 {
        format!("{x:.1}")
    } else {
        format!("{x}")
    }
}

fn fmt_v(v: [f64; 3]) -> String {
    format!("[{}, {}, {}]", fmt_num(v[0]), fmt_num(v[1]), fmt_num(v[2]))
}

/// Standard file header: background + camera + 3 lights.
pub fn gen_header(camera_pos: [f64; 3], camera_target: [f64; 3]) -> String {
    format!(
        "// generated by cgs_gen — do not hand-edit, regenerate from spec\n\
         background(color=0x2B3138);\n\
         camera(fov=45, position={}, target={});\n\
         directional_light(direction=[0.4, 1.0, 0.5], intensity=0.5);\n\
         point_light(position=[-5, 6, 4], intensity=0.55);\n\
         ambient_light(intensity=0.38);\n",
        fmt_v(camera_pos),
        fmt_v(camera_target)
    )
}

/// A vertical post (local +Z cylinder rotated flat onto +Y), like `post()` in mechanical.cgs.
pub fn gen_post(r: f64, h: f64) -> String {
    format!(
        "rotate(axis=[1.0, 0.0, 0.0], angle=-1.5707963267948966) cylinder(r={}, h={});",
        fmt_num(r),
        fmt_num(h)
    )
}

#[derive(Clone, Copy, Debug)]
pub struct FlangeSpec {
    pub r_disc: f64,
    pub h_disc: f64,
    pub n_holes: u32,
    pub hole_circle_r: f64,
    pub hole_r: f64,
    pub hole_h: f64,
    pub center_hole_r: f64,
    pub color: u32,
}

impl Default for FlangeSpec {
    fn default() -> Self {
        Self {
            r_disc: 2.6,
            h_disc: 0.5,
            n_holes: 8,
            hole_circle_r: 2.0,
            hole_r: 0.16,
            hole_h: 2.0,
            center_hole_r: 0.58,
            color: 0x9BA1A6,
        }
    }
}

/// Flange disc with `n_holes` true-drill holes on a bolt circle + center bore.
pub fn gen_flange(s: &FlangeSpec) -> String {
    let mut out = format!(
        "material(color=0x{:06X}, roughness=0.35, metalness=0.75)\ndifference() {{\n  {}\n",
        s.color,
        gen_post(s.r_disc, s.h_disc)
    );
    for i in 0..s.n_holes {
        let a = i as f64 * 2.0 * std::f64::consts::PI / s.n_holes as f64;
        out.push_str(&format!(
            "  rotate(axis=[0.0, 1.0, 0.0], angle={}) translate([{}, 0.0, 0.0]) {}\n",
            fmt_num(a),
            fmt_num(s.hole_circle_r),
            gen_post(s.hole_r, s.hole_h)
        ));
    }
    out.push_str(&format!("  {}\n}}\n", gen_post(s.center_hole_r, s.hole_h)));
    out
}

#[derive(Clone, Copy, Debug)]
pub struct BoltCircleSpec {
    pub n: u32,
    pub radius: f64,
    pub y: f64,
    pub bolt_r: f64,
    pub bolt_h: f64,
    pub color: u32,
}

impl Default for BoltCircleSpec {
    fn default() -> Self {
        Self {
            n: 8,
            radius: 2.0,
            y: 0.55,
            bolt_r: 0.13,
            bolt_h: 0.7,
            color: 0x6E747A,
        }
    }
}

/// Ring of bolts (shaft post + hex-head-ish box cap each).
pub fn gen_bolt_circle(s: &BoltCircleSpec) -> String {
    let mut out = String::new();
    for i in 0..s.n {
        let a = i as f64 * 2.0 * std::f64::consts::PI / s.n as f64;
        let hw = s.bolt_r * 3.2;
        out.push_str(&format!(
            "rotate(axis=[0.0, 1.0, 0.0], angle={}) translate([{}, {}, 0.0]) {{\n  material(color=0x{:06X}, roughness=0.4, metalness=0.7) {}\n  translate([0.0, {}, 0.0]) material(color=0x{:06X}, roughness=0.4, metalness=0.7) box(s=[{}, 0.18, {}]);\n}}\n",
            fmt_num(a),
            fmt_num(s.radius),
            fmt_num(s.y),
            s.color,
            gen_post(s.bolt_r, s.bolt_h),
            fmt_num(s.bolt_h / 2.0 + 0.09),
            s.color,
            fmt_num(hw),
            fmt_num(hw)
        ));
    }
    out
}

#[derive(Clone, Copy, Debug)]
pub struct GearSpec {
    pub y: f64,
    pub r_hub: f64,
    pub r_teeth: f64,
    pub n_teeth: u32,
    pub thick: f64,
    pub color: u32,
}

impl Default for GearSpec {
    fn default() -> Self {
        Self {
            y: 2.6,
            r_hub: 1.15,
            r_teeth: 1.75,
            n_teeth: 16,
            thick: 0.45,
            color: 0xC8A24A,
        }
    }
}

/// Hub post + radial tooth boxes.
pub fn gen_gear(s: &GearSpec) -> String {
    let mut out = format!(
        "translate([0.0, {}, 0.0]) material(color=0x{:06X}, roughness=0.3, metalness=0.8) {}\n",
        fmt_num(s.y),
        s.color,
        gen_post(s.r_hub, s.thick)
    );
    for i in 0..s.n_teeth {
        let a = i as f64 * 2.0 * std::f64::consts::PI / s.n_teeth as f64;
        out.push_str(&format!(
            "rotate(axis=[0.0, 1.0, 0.0], angle={}) translate([{}, {}, 0.0]) material(color=0x{:06X}, roughness=0.3, metalness=0.8) box(s=[{}, {}, 0.22]);\n",
            fmt_num(a),
            fmt_num(s.r_hub + (s.r_teeth - s.r_hub) / 2.0),
            fmt_num(s.y),
            s.color,
            fmt_num(s.r_teeth - s.r_hub + 0.12),
            fmt_num(s.thick)
        ));
    }
    out
}

#[derive(Clone, Copy, Debug)]
pub struct BasePlateSpec {
    pub size: f64,
    pub thick: f64,
    pub hole_offset: f64,
    pub sink_r: f64,
    pub sink_h: f64,
    pub color: u32,
}

impl Default for BasePlateSpec {
    fn default() -> Self {
        Self {
            size: 7.0,
            thick: 0.3,
            hole_offset: 2.9,
            sink_r: 0.32,
            sink_h: 0.35,
            color: 0x4A4F54,
        }
    }
}

/// Base plate with 4 corner countersink (cone) cutouts.
pub fn gen_base_plate(s: &BasePlateSpec) -> String {
    let mut out = format!(
        "material(color=0x{:06X}, roughness=0.5, metalness=0.6)\ndifference() {{\n  box(s=[{}, {}, {}]);\n",
        s.color,
        fmt_num(s.size),
        fmt_num(s.thick),
        fmt_num(s.size)
    );
    for i in 0..4 {
        let a = i as f64 * std::f64::consts::PI / 2.0 + std::f64::consts::PI / 4.0;
        out.push_str(&format!(
            "  rotate(axis=[0.0, 1.0, 0.0], angle={}) translate([{}, 0.0, 0.0]) rotate(axis=[1.0, 0.0, 0.0], angle={}) cone(r={}, h={});\n",
            fmt_num(a),
            fmt_num(s.hole_offset),
            fmt_num(std::f64::consts::PI / 2.0),
            fmt_num(s.sink_r),
            fmt_num(s.sink_h)
        ));
    }
    out.push_str("}\n");
    out
}

/// Full flange assembly file, mirroring `examples/cgs/mechanical.cgs`.
pub fn gen_flange_assembly(
    flange: &FlangeSpec,
    bolts: &BoltCircleSpec,
    gear: &GearSpec,
    plate: &BasePlateSpec,
) -> String {
    let mut out = gen_header([7.5, 6.5, 9.5], [0.0, 1.8, 0.0]);
    out.push_str(&format!(
        "translate([0.0, 0.15, 0.0]) {{\n{}}}\n",
        gen_base_plate(plate)
    ));
    out.push_str(&format!(
        "translate([0.0, 0.55, 0.0]) {{\n{}}}\n",
        gen_flange(flange)
    ));
    out.push_str(&gen_bolt_circle(bolts));
    out.push_str(&format!(
        "translate([0.0, 2.9, 0.0]) material(color=0x9BA1A6, roughness=0.3, metalness=0.8) {}\n",
        gen_post(0.55, 4.2)
    ));
    out.push_str(&format!(
        "translate([0.0, 1.25, 0.0]) material(color=0x9BA1A6, roughness=0.3, metalness=0.8) {}\n",
        gen_post(0.85, 0.9)
    ));
    out.push_str(&gen_gear(gear));
    out.push_str(
        "translate([0.0, 4.45, 0.0]) rotate(axis=[1.0, 0.0, 0.0], angle=-1.5707963267948966) material(color=0x4A4F54, roughness=0.45, metalness=0.65) torus(R=0.72, r=0.16);\n\
         translate([0.0, 4.85, 0.0]) material(color=0x6E747A, roughness=0.4, metalness=0.7) box(s=[0.95, 0.5, 0.95]);\n\
         translate([0.62, 3.6, 0.0]) material(color=0xC8A24A, roughness=0.35, metalness=0.75) box(s=[0.18, 0.9, 0.18]);\n\
         material(color=0x3A4046, roughness=0.9) plane(n=[0.0, 1.0, 0.0], d=0.0);\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn post_golden() {
        assert_eq!(
            gen_post(2.6, 0.5),
            "rotate(axis=[1.0, 0.0, 0.0], angle=-1.5707963267948966) cylinder(r=2.6, h=0.5);"
        );
    }

    #[test]
    fn flange_has_all_holes_unrolled() {
        let s = FlangeSpec::default();
        let t = gen_flange(&s);
        assert!(t.contains("difference()"));
        // 8 bolt holes + 1 center hole + 1 disc = 10 cylinder() calls
        assert_eq!(t.matches("cylinder(").count(), 10);
        assert!(t.contains("material(color=0x9BA1A6"));
    }

    #[test]
    fn generated_assembly_parses_and_counts() {
        let text = gen_flange_assembly(
            &FlangeSpec::default(),
            &BoltCircleSpec::default(),
            &GearSpec::default(),
            &BasePlateSpec::default(),
        );
        let (scene, _cam) = crate::cgs_load_result(&text, ".").expect("generated CGS must parse");
        // base(1) + flange(1) + bolts 8x2 + shaft + shoulder + hub + 16 teeth
        // + washer + nut + key + ground = 41 meshes
        assert_eq!(scene.objects.len(), 41);
    }

    #[test]
    fn gear_tooth_count() {
        let t = gen_gear(&GearSpec::default());
        assert_eq!(t.matches("box(s=").count(), 16);
    }
}
