"""Wavefront OBJ 读写 (仅几何: v / f / o 行)。

限制 (如实标注):
  - 忽略 vt/vn/材质 (mtllib/usemtl) 与线/点元素 (l/p), 只保留三角化后的面。
  - 所有 o/g 组合并为一张网格返回, 不保留分组信息。
  - 多边形面 (>3 顶点) 按扇形三角化, 假定多边形为简单凸环。
"""

from pathlib import Path

from cga.mesh_io._common import Mat4, Mesh, Tri, Vec3, transform_point

__all__ = ["load_obj", "save_obj"]

ObjMeshIn = tuple[list[Vec3], list[Tri], Mat4 | None]
"""save_obj 输入条目: ``(vertices, faces, transform|None)``。"""


def _resolve_index(token: str, vertex_count: int, lineno: int) -> int:
    """把 OBJ 的 1 基/负索引顶点引用解析为 0 基索引并校验越界。"""
    ref = token.split("/")[0]
    if not ref:
        raise ValueError(f"第 {lineno} 行: 面顶点引用为空")
    try:
        raw = int(ref)
    except ValueError:
        raise ValueError(f"第 {lineno} 行: 非法顶点索引 {ref!r}") from None
    if raw == 0:
        raise ValueError(f"第 {lineno} 行: OBJ 索引为 1 基, 不允许 0")
    idx = vertex_count + raw if raw < 0 else raw - 1
    if idx < 0 or idx >= vertex_count:
        raise ValueError(
            f"第 {lineno} 行: 顶点索引 {raw} 越界 (当前共 {vertex_count} 个顶点)"
        )
    return idx


def load_obj(path: str | Path) -> Mesh:
    """解析 OBJ 文件, 返回 ``(vertices, faces)``。

    支持 f 行的 ``a`` / ``a/b`` / ``a/b/c`` 三种顶点引用与负索引;
    所有 o/g 组顶点汇入同一列表; 忽略 vt/vn/材质。
    空面 (<3 顶点) 或越界索引抛出 ValueError。
    """
    text = Path(path).read_text(encoding="utf-8")
    vertices: list[Vec3] = []
    faces: list[Tri] = []
    for lineno, raw_line in enumerate(text.splitlines(), start=1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        keyword, fields = parts[0], parts[1:]
        if keyword == "v":
            if len(fields) < 3:
                raise ValueError(f"第 {lineno} 行: v 行需要至少 3 个坐标")
            vertices.append((float(fields[0]), float(fields[1]), float(fields[2])))
        elif keyword == "f":
            indices = [_resolve_index(tok, len(vertices), lineno) for tok in fields]
            if len(indices) < 3:
                raise ValueError(f"第 {lineno} 行: 空面 (顶点数 < 3)")
            # 扇形三角化: (0, i, i+1)。
            for i in range(1, len(indices) - 1):
                faces.append((indices[0], indices[i], indices[i + 1]))
        # 其它关键字 (vt/vn/o/g/s/mtllib/usemtl/l/p) 一律忽略。
    return vertices, faces


def save_obj(path: str | Path, meshes: list[ObjMeshIn]) -> None:
    """把多张网格写入一个 OBJ 文件。

    ``meshes`` 每项为 ``(vertices, faces, transform)``; transform 非 None
    时先把顶点烘到世界系再写出。每张网格一个 ``o mesh_<i>`` 组,
    f 行索引带全局偏移 (OBJ 为 1 基)。
    """
    lines: list[str] = ["# generated by cga.mesh_io"]
    offset = 0
    for mesh_index, (vertices, faces, transform) in enumerate(meshes):
        lines.append(f"o mesh_{mesh_index}")
        for p in vertices:
            x, y, z = transform_point(transform, p) if transform is not None else p
            lines.append(f"v {x:.9g} {y:.9g} {z:.9g}")
        for a, b, c in faces:
            lines.append(f"f {a + 1 + offset} {b + 1 + offset} {c + 1 + offset}")
        offset += len(vertices)
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
