#!/usr/bin/env python3
"""One-off generator: parse ../../../multivector_tables.v and emit src/tables.rs.

The V file was machine-generated by gen/gen_tables.py; this script just
transliterates the const arrays into Rust `pub const` declarations, keeping
the original snake_case names and values.

NOTE: the V sources were removed when the project moved to Rust (they remain
in git history). The generated src/tables.rs is checked in and stable — the
GP table is a mathematical constant — so this script is kept for provenance
only and does not need to be re-run.
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
V_FILE = HERE.parents[1] / "multivector_tables.v"  # crates/cga-core -> repo root
OUT = HERE / "src" / "tables.rs"

HEADER = """// Code generated by gen_tables.py from multivector_tables.v; do not edit by hand.
// Geometric-product table and grade masks for 5D CGA over the null basis
// {e1, e2, e3, e0, einf}, matching cga/multivector.py exactly.
#![allow(non_upper_case_globals)]
"""

if not V_FILE.exists():
    raise SystemExit(
        f"{V_FILE} no longer exists (V sources removed; recoverable from git\n"
        "history via `git show HEAD~N:multivector_tables.v`). The generated\n"
        "src/tables.rs is checked in and stable — re-running is unnecessary."
    )

src = V_FILE.read_text()

# Scalar consts: `pub const name = 32`
scalars = re.findall(r"pub const (\w+) = (\d+)\s*\n", src)
# Array consts: `pub const name = [ ... ]`
arrays = re.findall(r"pub const (\w+) = \[(.*?)\]", src, re.DOTALL)

out = [HEADER]

for name, value in scalars:
    out.append(f"pub const {name}: usize = {value};\n")

for name, body in arrays:
    if "'" in body:
        # String table (basis_names).
        names = re.findall(r"'([^']*)'", body)
        lines = ",\n".join(f'    "{n}"' for n in names)
        out.append(f"pub const {name}: [&str; {len(names)}] = [\n{lines},\n];\n")
        continue
    tokens = [t.strip() for t in body.replace("\n", " ").split(",") if t.strip()]
    is_float = any("." in t for t in tokens)
    ty = "f64" if is_float else "usize"
    rows = []
    for i in range(0, len(tokens), 8):
        rows.append("    " + ", ".join(tokens[i : i + 8]) + ",")
    out.append(
        f"pub const {name}: [{ty}; {len(tokens)}] = [\n" + "\n".join(rows) + "\n];\n"
    )

OUT.write_text("\n".join(out))
print(f"wrote {OUT}")
