#!/usr/bin/env python3
"""One-off generator: transliterate a CGA multiplication-table definition (const
arrays in `pub const name = ...` form) into src/tables.rs, keeping the original
snake_case names and values.

The generated src/tables.rs is checked in and stable — the GP table is a
mathematical constant — so this script is kept for provenance only and does not
normally need to be re-run.

Usage: gen_tables.py <table_source>
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "src" / "tables.rs"

HEADER = """// Code generated by gen_tables.py; do not edit by hand.
// Geometric-product table and grade masks for 5D CGA over the null basis
// {e1, e2, e3, e0, einf}, matching cga/multivector.py exactly.
#![allow(non_upper_case_globals)]
"""

if len(sys.argv) < 2:
    raise SystemExit(
        "usage: gen_tables.py <table_source>\n"
        "src/tables.rs is checked in and stable — regeneration is only needed if\n"
        "the multiplication-table definition itself changes."
    )

src = Path(sys.argv[1]).read_text()

# Scalar consts: `pub const name = 32`
scalars = re.findall(r"pub const (\w+) = (\d+)\s*\n", src)
# Array consts: `pub const name = [ ... ]`
arrays = re.findall(r"pub const (\w+) = \[(.*?)\]", src, re.DOTALL)

out = [HEADER]

for name, value in scalars:
    out.append(f"pub const {name}: usize = {value};\n")

for name, body in arrays:
    if "'" in body:
        # String table (basis_names).
        names = re.findall(r"'([^']*)'", body)
        lines = ",\n".join(f'    "{n}"' for n in names)
        out.append(f"pub const {name}: [&str; {len(names)}] = [\n{lines},\n];\n")
        continue
    tokens = [t.strip() for t in body.replace("\n", " ").split(",") if t.strip()]
    is_float = any("." in t for t in tokens)
    ty = "f64" if is_float else "usize"
    rows = []
    for i in range(0, len(tokens), 8):
        rows.append("    " + ", ".join(tokens[i : i + 8]) + ",")
    out.append(
        f"pub const {name}: [{ty}; {len(tokens)}] = [\n" + "\n".join(rows) + "\n];\n"
    )

OUT.write_text("\n".join(out))
print(f"wrote {OUT}")
