#!/usr/bin/env python3
"""Generate the static CGA algebra tables from the authoritative Python core.

Run from the repo root:
    .venv/bin/python cga-c/tools/gen_tables.py > cga-c/src/gp_tables.h

The C core (cga-c/) reuses the exact same basis ordering and geometric-product
table that cga.multivector computes, so the C port cannot drift from the
Python semantics.
"""
import cga.multivector as M

mv = M.Multivector

max_terms = max(len(t) for row in mv.GP_TABLE for t in row)
assert max_terms <= 2, max_terms

counts = [[len(mv.GP_TABLE[i][j]) for j in range(32)] for i in range(32)]
signs = [[[mv.GP_TABLE[i][j][k][0] if k < len(mv.GP_TABLE[i][j]) else 0
           for k in range(max_terms)] for j in range(32)] for i in range(32)]
dsts = [[[mv.GP_TABLE[i][j][k][1] if k < len(mv.GP_TABLE[i][j]) else 0
          for k in range(max_terms)] for j in range(32)] for i in range(32)]

reverse_mask = [int(v) for v in mv.REVERSE_MASK.tolist()]
involution_mask = [int(v) for v in mv.INVOLUTION_MASK.tolist()]
grade_masks = [mv.GRADE_MASKS[g].tolist() for g in range(mv.NUM_GRADES)]
grade_slices = mv.GRADE_SLICES
euc_indices = [0, 1, 2, 3, 6, 7, 10, 16]


def emit_counts():
    out = ["static const uint8_t CGA_GP_COUNT[32][32] = {"]
    for i in range(32):
        out.append("  {" + ", ".join(str(counts[i][j]) for j in range(32)) + "},")
    out.append("};")
    return "\n".join(out)


def emit_terms(name, table):
    out = [f"static const int8_t {name}[32][32][{max_terms}] = {{"]
    for i in range(32):
        rows = []
        for j in range(32):
            rows.append("{" + ", ".join(str(table[i][j][k]) for k in range(max_terms)) + "}")
        out.append("  {" + ", ".join(rows) + "},")
    out.append("};")
    return "\n".join(out)


def emit_mask(name, data):
    out = [f"static const int8_t {name}[32] = {{"]
    for v in data:
        out.append(f"  {int(v)},")
    out.append("};")
    return "\n".join(out)


print("/* Auto-generated by cga-c/tools/gen_tables.py — do not edit. */")
print("#ifndef CCGA_GP_TABLES_H")
print("#define CCGA_GP_TABLES_H")
print("#include <stdint.h>")
print()
print(f"#define CCGA_GP_MAX_TERMS {max_terms}")
print()
print(emit_counts())
print()
print(emit_terms("CGA_GP_SIGN", signs))
print()
print(emit_terms("CGA_GP_DST", dsts))
print()
print(emit_mask("CGA_REVERSE_MASK", reverse_mask))
print()
print(emit_mask("CGA_INVOLUTION_MASK", involution_mask))
print()
print("static const float CGA_GRADE_MASK[6][32] = {")
for g in range(6):
    print("  {" + ", ".join(f"{float(v):.1f}f" for v in grade_masks[g]) + "},")
print("};")
print()
print("/* GRADE_SLICES[g] = {start, end} into the 32-component layout */")
print("static const int CGA_GRADE_SLICE_START[6] = {" + ", ".join(str(s) for s, _ in grade_slices) + "};")
print("static const int CGA_GRADE_SLICE_END[6] = {" + ", ".join(str(e) for _, e in grade_slices) + "};")
print()
print("/* Bulk (Euclidean) component indices: blades containing no e0/e∞ */")
print("static const int CGA_BULK_INDICES[8] = {" + ", ".join(str(i) for i in euc_indices) + "};")
print()
print("#endif /* CCGA_GP_TABLES_H */")
