#!/usr/bin/env node
// 内置 React 运行时（可复现）。用法：node scripts/vendor-react.mjs
//
// 产物（提交进仓库，供 cga-host 在 boa 里加载）：
//   crates/cga-host/assets/react-runtime.dev.js   开发构建：带 invalid hook call 等诊断
//   crates/cga-host/assets/react-runtime.prod.js  生产构建（minify）：批量渲染/CI
//
// 两个产物都不含宿主适配层与调度器替身，那两份是我们自己的源码：
//   crates/cga-host/assets/react-shim.js  平台层（确定性 setTimeout/microtask/performance/console）
//   crates/cga-host/assets/react-host.js  渲染器适配层（host config + 会话）
// 加载顺序必须是 shim → runtime → host（scheduler 在模块初始化时探测全局）。

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..');
const OUT_DIR = join(REPO, 'crates/cga-host/assets');

const PINNED = {
  react: '19.3.0',
  'react-reconciler': '0.34.0',
  scheduler: '0.28.0',
};
const ESBUILD = '0.24.0';

const work = mkdtempSync(join(tmpdir(), 'cga-vendor-react-'));
writeFileSync(join(work, 'package.json'), JSON.stringify({ name: 'vendor', private: true, type: 'module' }));
copyFileSync(join(HERE, 'react-runtime-entry.mjs'), join(work, 'entry.mjs'));

const pins = Object.entries(PINNED).map(([k, v]) => `${k}@${v}`);
console.log(`npm install ${pins.join(' ')}`);
execFileSync('npm', ['install', '--silent', '--no-save', ...pins], { cwd: work, stdio: 'inherit' });

const header = (env) =>
  `// GENERATED by scripts/vendor-react.mjs — do not edit.\n` +
  `// ${Object.entries(PINNED).map(([k, v]) => `${k}@${v}`).join(' ')}\n` +
  `// esbuild@${ESBUILD} --target=es2019 --format=iife NODE_ENV=${env}\n`;

function build(env, outfile, extra) {
  const out = join(work, outfile);
  execFileSync(
    'npx',
    [
      '--yes',
      `esbuild@${ESBUILD}`,
      'entry.mjs',
      '--bundle',
      '--format=iife',
      '--target=es2019',
      `--define:process.env.NODE_ENV='"${env}"'`,
      `--outfile=${out}`,
      '--log-level=warning',
      ...extra,
    ],
    { cwd: work, stdio: 'inherit' },
  );
  const code = readFileSync(out, 'utf8');
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, outfile.replace('out.', 'react-runtime.')), header(env) + code);
  return code.length;
}

const dev = build('development', 'out.dev.js', []);
const prod = build('production', 'out.prod.js', ['--minify']);
const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
console.log(`wrote react-runtime.dev.js (${kb(dev)}) and react-runtime.prod.js (${kb(prod)}) into ${OUT_DIR}`);
