//! 5D Conformal Geometric Algebra (CGA) multivector representation.
//!
//! A multivector has 32 components organised by grade:
//!   grade 0: 1 scalar
//!   grade 1: 5 vectors  {e1, e2, e3, e0, einf}
//!   grade 2: 10 bivectors
//!   grade 3: 10 trivectors
//!   grade 4: 5 quadvectors
//!   grade 5: 1 pseudoscalar
//!
//! The basis is the null basis {e1, e2, e3, e0, einf}: e0^2 = einf^2 = 0 and
//! e0.einf = -1.  Component slot 4 is the e0 coefficient, slot 5 the einf
//! coefficient, so the conformal weight of a point is stored explicitly (no
//! basis-change cancellation at far origins).
//!
//! Unlike the Python reference (which stores components in MLX arrays), the 32
//! coefficients live in a plain fixed `[32]f64` array and the algebra runs on
//! the CPU in full double precision.  The geometric-product table is the exact
//! same table as `cga/multivector.py`, generated by `gen/gen_tables.py` into
//! `src/tables.rs`.  The render kernel is float32, exactly as in the reference.

use crate::tables::*;
use std::fmt;

#[derive(Clone, Copy, Debug)]
pub struct Multivector {
    pub values: [f64; 32],
}

// --- constructors -----------------------------------------------------------

/// mv_zero returns the zero multivector.
pub fn mv_zero() -> Multivector {
    Multivector {
        values: [0.0; num_components],
    }
}

/// mv_scalar returns a scalar multivector (only the grade-0 component).
pub fn mv_scalar(s: f64) -> Multivector {
    let mut m = mv_zero();
    m.values[0] = s;
    m
}

/// mv_vector builds a vector from euclidean components (v1,v2,v3) plus the
/// e0/einf coefficients (v0/ve).
pub fn mv_vector(v1: f64, v2: f64, v3: f64, v0: f64, ve: f64) -> Multivector {
    let mut m = mv_zero();
    m.values[1] = v1;
    m.values[2] = v2;
    m.values[3] = v3;
    m.values[4] = v0;
    m.values[5] = ve;
    m
}

/// mv_bivector builds a bivector from 10 grade-2 components in canonical order.
pub fn mv_bivector(components: [f64; 10]) -> Multivector {
    let mut m = mv_zero();
    for i in 0..10 {
        m.values[grade_indices[grade_start[2] + i]] = components[i];
    }
    m
}

// Basis vectors (grade-1).  Fresh values per call; the coefficients are exact.
pub fn e1() -> Multivector {
    mv_vector(1.0, 0.0, 0.0, 0.0, 0.0)
}

pub fn e2() -> Multivector {
    mv_vector(0.0, 1.0, 0.0, 0.0, 0.0)
}

pub fn e3() -> Multivector {
    mv_vector(0.0, 0.0, 1.0, 0.0, 0.0)
}

pub fn e0() -> Multivector {
    mv_vector(0.0, 0.0, 0.0, 1.0, 0.0)
}

pub fn einf() -> Multivector {
    mv_vector(0.0, 0.0, 0.0, 0.0, 1.0)
}

impl Multivector {
    // --- component access ---------------------------------------------------

    /// grade returns the grade-g projection.
    pub fn grade(&self, g: usize) -> Multivector {
        let mut res = mv_zero();
        for &idx in &grade_indices[grade_start[g]..grade_start[g + 1]] {
            res.values[idx] = self.values[idx];
        }
        res
    }

    /// scalar_part returns the grade-0 component.
    pub fn scalar_part(&self) -> f64 {
        self.values[0]
    }

    /// vector_part returns the 5 grade-1 components.
    pub fn vector_part(&self) -> [f64; 5] {
        [
            self.values[1],
            self.values[2],
            self.values[3],
            self.values[4],
            self.values[5],
        ]
    }

    /// euclidean_vector returns the e1/e2/e3 coefficients.
    pub fn euclidean_vector(&self) -> [f64; 3] {
        [self.values[1], self.values[2], self.values[3]]
    }

    /// e0_coeff returns the e0 (origin) coefficient — the conformal weight.
    pub fn e0_coeff(&self) -> f64 {
        self.values[4]
    }

    /// einf_coeff returns the einf (point at infinity) coefficient.
    pub fn einf_coeff(&self) -> f64 {
        self.values[5]
    }

    /// bivector_part returns the 10 grade-2 components.
    pub fn bivector_part(&self) -> [f64; 10] {
        let mut out = [0.0; 10];
        for i in 0..10 {
            out[i] = self.values[grade_indices[grade_start[2] + i]];
        }
        out
    }

    /// coords returns the weight-normalised euclidean coordinates of a
    /// conformal point (x, y, z) = (v1, v2, v3) / e0_coeff.
    pub fn coords(&self) -> [f64; 3] {
        let w = self.values[4];
        if w.abs() < 1e-12 {
            panic!("multivector has no e0 component; not a finite point");
        }
        [self.values[1] / w, self.values[2] / w, self.values[3] / w]
    }

    /// is_zero reports whether all components are approximately zero.
    /// (This is not CGA nullity — a conformal point is a null vector but not
    /// zero.)
    pub fn is_zero(&self) -> bool {
        for v in self.values {
            if v.abs() > 1e-10 {
                return false;
            }
        }
        true
    }

    /// vmax returns the maximum absolute component.
    pub fn vmax(&self) -> f64 {
        let mut mx = 0.0;
        for v in self.values {
            let a = v.abs();
            if a > mx {
                mx = a;
            }
        }
        mx
    }

    // --- operators ----------------------------------------------------------

    pub fn add(&self, o: &Multivector) -> Multivector {
        let mut res = mv_zero();
        for i in 0..num_components {
            res.values[i] = self.values[i] + o.values[i];
        }
        res
    }

    pub fn sub(&self, o: &Multivector) -> Multivector {
        let mut res = mv_zero();
        for i in 0..num_components {
            res.values[i] = self.values[i] - o.values[i];
        }
        res
    }

    pub fn mul_scalar(&self, s: f64) -> Multivector {
        let mut res = mv_zero();
        for i in 0..num_components {
            res.values[i] = self.values[i] * s;
        }
        res
    }

    pub fn div_scalar(&self, s: f64) -> Multivector {
        let mut res = mv_zero();
        for i in 0..num_components {
            res.values[i] = self.values[i] / s;
        }
        res
    }

    pub fn neg(&self) -> Multivector {
        let mut res = mv_zero();
        for i in 0..num_components {
            res.values[i] = -self.values[i];
        }
        res
    }

    /// approx_eq performs approximate equality (allclose, atol=1e-6).
    ///
    /// This is *not* `PartialEq::eq`: approximate equality is not transitive,
    /// so `Multivector` deliberately does not implement `PartialEq`.
    pub fn approx_eq(&self, o: &Multivector) -> bool {
        self.values
            .iter()
            .zip(&o.values)
            .all(|(&a, &b)| (a - b).abs() <= 1e-6)
    }

    /// copy returns a fresh multivector with the same components.
    pub fn copy(&self) -> Multivector {
        *self
    }

    // --- algebra ------------------------------------------------------------

    /// gp computes the geometric product using the precomputed sparse table.
    pub fn gp(&self, o: &Multivector) -> Multivector {
        let mut res = mv_zero();
        for i in 0..num_components {
            let a = self.values[i];
            if a == 0.0 {
                continue;
            }
            for k in gp_row_start[i]..gp_row_start[i + 1] {
                let b = o.values[gp_j[k]];
                if b == 0.0 {
                    continue;
                }
                res.values[gp_dst[k]] += gp_sign[k] * a * b;
            }
        }
        res
    }

    /// ip computes the fat-dot inner product (Hestenes), matching clifford's
    /// `|`.
    ///
    /// A|B = sum_{r,s>=1} < <A>_r * <B>_s >_|r-s| ; scalar (grade-0) terms are
    /// zero.
    pub fn ip(&self, o: &Multivector) -> Multivector {
        let mut res = mv_zero();
        for ga in 1..num_grades {
            let a_g = self.grade(ga);
            if a_g.is_zero() {
                continue;
            }
            for gb in 1..num_grades {
                let b_g = o.grade(gb);
                if b_g.is_zero() {
                    continue;
                }
                let prod = a_g.gp(&b_g);
                res = res.add(&prod.grade((gb as i64 - ga as i64).unsigned_abs() as usize));
            }
        }
        res
    }

    /// op computes the outer product.
    ///
    /// a ^ b = sum_{r,s} < <a>_r * <b>_s >_{r+s}
    pub fn op(&self, o: &Multivector) -> Multivector {
        let mut res = mv_zero();
        for ga in 0..num_grades {
            let a_g = self.grade(ga);
            if a_g.is_zero() {
                continue;
            }
            for gb in 0..num_grades - ga {
                let b_g = o.grade(gb);
                if b_g.is_zero() {
                    continue;
                }
                let prod = a_g.gp(&b_g);
                res = res.add(&prod.grade(ga + gb));
            }
        }
        res
    }

    /// reverse applies the reversal involution: grade-k blade * (-1)^(k(k-1)/2).
    pub fn reverse(&self) -> Multivector {
        let mut res = mv_zero();
        for (r, (&v, &m)) in res
            .values
            .iter_mut()
            .zip(self.values.iter().zip(&reverse_mask))
        {
            *r = v * m;
        }
        res
    }

    /// grade_involution flips the sign of odd-grade components.
    pub fn grade_involution(&self) -> Multivector {
        let mut res = mv_zero();
        for (r, (&v, &m)) in res
            .values
            .iter_mut()
            .zip(self.values.iter().zip(&involution_mask))
        {
            *r = v * m;
        }
        res
    }

    /// conjugate is the Clifford conjugate (reverse + grade involution).
    pub fn conjugate(&self) -> Multivector {
        self.reverse().grade_involution()
    }

    /// dual is the Hodge dual: multiply by I^-1 = -blade31.  On this null
    /// basis the pseudoscalar I = e1e2e3e0einf squares to -1, so I^-1 = -I.
    pub fn dual(&self) -> Multivector {
        let mut i_inv = mv_zero();
        i_inv.values[31] = -1.0;
        self.gp(&i_inv)
    }

    /// undual inverts dual (dual(dual(x)) = -x, so undual = -dual).
    pub fn undual(&self) -> Multivector {
        self.dual().neg()
    }

    /// meet returns the regressive product (self* ^ o*)* — the geometric
    /// intersection of two blades.  When the duals wedge to zero (contained or
    /// parallel blades) it falls back to the linear intersection of the two
    /// blade subspaces, which is exact for direct-form blades (CGA
    /// points/lines/planes and any purely linear blade) and returns the
    /// contained blade, e.g. meet(e12, e13) = e1 and meet(e12, e23) = e2.
    /// Non-blade inputs panic.
    pub fn meet(&self, o: &Multivector) -> Multivector {
        if self.is_zero() || o.is_zero() {
            return mv_zero();
        }
        let ga = self.blade_grade();
        let gb = o.blade_grade();
        if ga < 0 || gb < 0 {
            panic!("meet: arguments must be blades");
        }
        if ga == 0 || gb == 0 {
            return mv_zero();
        }
        let w = self.dual().op(&o.dual());
        if !w.is_zero() {
            return w.dual();
        }
        // The duals share a factor: intersection of the linear spans.
        let na = nullspace(&rows_of_mask(blade_mask(self)));
        let nb = nullspace(&rows_of_mask(blade_mask(o)));
        let mut merged = na;
        merged.extend(nb);
        let c = nullspace(&merged);
        if c.is_empty() {
            return mv_zero();
        }
        wedge_rows(&c)
    }

    /// join returns the smallest blade spanning both self and o: the union of
    /// their blade subspaces.  Non-blade inputs panic; scalar or zero inputs
    /// join as the other blade.
    pub fn join(&self, o: &Multivector) -> Multivector {
        if self.is_zero() {
            return *o;
        }
        if o.is_zero() {
            return *self;
        }
        let ga = self.blade_grade();
        let gb = o.blade_grade();
        if ga < 0 || gb < 0 {
            panic!("join: arguments must be blades");
        }
        if ga == 0 {
            return *o;
        }
        if gb == 0 {
            return *self;
        }
        let mut rows = rows_of_mask(blade_mask(self));
        rows.extend(rows_of_mask(blade_mask(o)));
        wedge_rows(&row_basis(&rows))
    }

    /// norm returns the euclidean norm sqrt(|<self.reverse(self)>_0|).
    pub fn norm(&self) -> f64 {
        let s = self.gp(&self.reverse()).values[0];
        s.abs().sqrt()
    }

    /// normalized returns the unit-norm multivector (or zero if degenerate).
    pub fn normalized(&self) -> Multivector {
        let n = self.norm();
        if n < 1e-12 {
            return mv_zero();
        }
        self.div_scalar(n)
    }

    /// bulk returns the euclidean part (components without e0/einf).
    pub fn bulk(&self) -> Multivector {
        let mut res = mv_zero();
        for idx in [0, 1, 2, 3, 6, 7, 10, 16] {
            res.values[idx] = self.values[idx];
        }
        res
    }

    /// weight returns the conformal part (components containing e0/einf).
    pub fn weight(&self) -> Multivector {
        self.sub(&self.bulk())
    }

    // --- blade ops (inverse, projections, contractions) ----------------------

    /// blade_grade returns the grade of a pure blade, or -1 when the
    /// multivector holds mixed grades or is zero.
    fn blade_grade(&self) -> i32 {
        let mut g = -1;
        for (&v, &slot) in self.values.iter().zip(&slot_mask) {
            if v != 0.0 {
                let gi = bit_count(slot);
                if g != -1 && gi != g {
                    return -1;
                }
                g = gi;
            }
        }
        g
    }

    /// inverse returns A^-1 = rev(A)/(A rev(A))_0 for an invertible blade or
    /// versor; a general multivector with a non-scalar A*rev(A) panics.
    pub fn inverse(&self) -> Multivector {
        let prod = self.gp(&self.reverse());
        let s = prod.values[0];
        if s.abs() < 1e-12 || !prod.grade(0).approx_eq(&prod) {
            panic!("inverse: only blades and versors with nonzero norm are supported");
        }
        self.reverse().div_scalar(s)
    }

    /// lc is the left contraction A _| B: sums of <_A_g _B_h>_(h-g) for
    /// g <= h.
    pub fn lc(&self, o: &Multivector) -> Multivector {
        let mut res = mv_zero();
        for ga in 1..num_grades {
            let a_g = self.grade(ga);
            if a_g.is_zero() {
                continue;
            }
            for gb in ga..num_grades {
                let b_g = o.grade(gb);
                if b_g.is_zero() {
                    continue;
                }
                res = res.add(&a_g.gp(&b_g).grade(gb - ga));
            }
        }
        res
    }

    /// rc is the right contraction A |_ B: sums of <_A_g _B_h>_(g-h) for
    /// g >= h.
    pub fn rc(&self, o: &Multivector) -> Multivector {
        let mut res = mv_zero();
        for ga in 1..num_grades {
            let a_g = self.grade(ga);
            if a_g.is_zero() {
                continue;
            }
            for gb in 1..ga + 1 {
                let b_g = o.grade(gb);
                if b_g.is_zero() {
                    continue;
                }
                res = res.add(&a_g.gp(&b_g).grade(ga - gb));
            }
        }
        res
    }

    /// commutator returns [self, o] = (self o - o self) / 2.
    pub fn commutator(&self, o: &Multivector) -> Multivector {
        self.gp(o).sub(&o.gp(self)).mul_scalar(0.5)
    }

    /// anticommutator returns {self, o} = (self o + o self) / 2.
    pub fn anticommutator(&self, o: &Multivector) -> Multivector {
        self.gp(o).add(&o.gp(self)).mul_scalar(0.5)
    }

    /// proj projects self onto the blade o: (self . o) o^-1.
    pub fn proj(&self, o: &Multivector) -> Multivector {
        self.ip(o).gp(&o.inverse())
    }

    /// rej returns the part of self orthogonal to the blade o.
    pub fn rej(&self, o: &Multivector) -> Multivector {
        self.sub(&self.proj(o))
    }

    /// reflect mirrors self across the plane with the given normal:
    /// v' = -n v n with n the normalized normal; works for vectors and blades.
    pub fn reflect(&self, normal: [f64; 3]) -> Multivector {
        let len2 = normal[0] * normal[0] + normal[1] * normal[1] + normal[2] * normal[2];
        if len2 < 1e-18 {
            panic!("reflect: zero normal");
        }
        let n = mv_vector(normal[0], normal[1], normal[2], 0.0, 0.0).div_scalar(len2.sqrt());
        n.gp(self).gp(&n).neg()
    }
}

/// str renders non-zero components by grade.
impl fmt::Display for Multivector {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut parts: Vec<String> = Vec::new();
        for g in 0..num_grades {
            for &idx in &grade_indices[grade_start[g]..grade_start[g + 1]] {
                let v = self.values[idx];
                if v.abs() <= 1e-10 {
                    continue;
                }
                let name = basis_names[idx];
                if name == "1" {
                    parts.push(format!("{v:.4}"));
                } else {
                    parts.push(format!("{v:+.4}*{name}"));
                }
            }
        }
        if parts.is_empty() {
            return write!(f, "Multivector(0)");
        }
        write!(f, "Multivector({})", parts.join(" "))
    }
}

// --- subspace helpers for meet/join ------------------------------------------

// slot_mask maps a component slot to its generator bitmask (e1=1, e2=2,
// e3=4, e0=8, einf=16).  Slots are ordered lexicographically by generator,
// not by bitmask, so the mask must be looked up, never computed.
#[allow(non_upper_case_globals)]
const slot_mask: [i32; 32] = [
    0, 1, 2, 4, 8, 16, // grade 0-1
    3, 5, 9, 17, 6, 10, 18, 12, 20, 24, // grade 2
    7, 11, 19, 13, 21, 25, 14, 22, 26, 28, // grade 3
    15, 23, 27, 29, 30, // grade 4
    31, // grade 5
];

// bit_count counts set bits of a small non-negative integer.
fn bit_count(x: i32) -> i32 {
    let mut n = 0;
    let mut v = x;
    while v > 0 {
        n += v & 1;
        v >>= 1;
    }
    n
}

// blade_mask returns the generator bitmask of a pure blade.
fn blade_mask(m: &Multivector) -> i32 {
    let mut mask = 0;
    for (&v, &slot) in m.values.iter().zip(&slot_mask) {
        if v != 0.0 {
            mask |= slot;
        }
    }
    mask
}

// rows_of_mask returns the generator basis vectors of a blade mask as rows.
fn rows_of_mask(mask: i32) -> Vec<Vec<f64>> {
    let mut rows: Vec<Vec<f64>> = Vec::new();
    for i in 0..5 {
        if mask & (1 << i) != 0 {
            let mut row = vec![0.0; 5];
            row[i] = 1.0;
            rows.push(row);
        }
    }
    rows
}

// row_basis reduces rows to RREF and returns the pivot rows, a basis of the
// row space.
fn row_basis(rows: &[Vec<f64>]) -> Vec<Vec<f64>> {
    let mut mat: Vec<Vec<f64>> = rows.to_vec();
    let mut pivots = 0;
    for col in 0..5 {
        let pivot = mat[pivots..]
            .iter()
            .position(|row| row[col].abs() > 1e-12)
            .map(|p| p + pivots);
        let Some(pivot) = pivot else {
            continue;
        };
        mat.swap(pivot, pivots);
        let scale = mat[pivots][col];
        for v in &mut mat[pivots][col..5] {
            *v /= scale;
        }
        let pivot_row = mat[pivots].clone();
        for (i, row) in mat.iter_mut().enumerate() {
            if i == pivots {
                continue;
            }
            let f = row[col];
            if f.abs() < 1e-12 {
                continue;
            }
            for (v, &pv) in row[col..5].iter_mut().zip(&pivot_row[col..5]) {
                *v -= f * pv;
            }
        }
        pivots += 1;
    }
    mat[..pivots].to_vec()
}

// nullspace returns a basis of the solutions x of rows . x = 0, i.e. the
// orthogonal complement of the row space.
fn nullspace(rows: &[Vec<f64>]) -> Vec<Vec<f64>> {
    let rref = row_basis(rows);
    let mut pivot_cols: Vec<usize> = Vec::new();
    for row in &rref {
        if let Some(c) = row.iter().position(|&v| v.abs() > 1e-12) {
            pivot_cols.push(c);
        }
    }
    let mut basis: Vec<Vec<f64>> = Vec::new();
    for fc in 0..5 {
        if pivot_cols.contains(&fc) {
            continue;
        }
        let mut v = vec![0.0; 5];
        v[fc] = 1.0;
        for (i, &pc) in pivot_cols.iter().enumerate() {
            v[pc] = -rref[i][fc];
        }
        basis.push(v);
    }
    basis
}

// wedge_rows wedges the given independent 5D vectors in order.
fn wedge_rows(rows: &[Vec<f64>]) -> Multivector {
    let mut res = mv_scalar(1.0);
    for row in rows {
        res = res.op(&mv_vector(row[0], row[1], row[2], row[3], row[4]));
    }
    res
}

#[cfg(test)]
mod tests {
    use crate::*;

    // close is the approximate-equality helper used by these tests.
    #[allow(dead_code)]
    fn close(a: f64, b: f64, tol: f64) -> bool {
        (a - b).abs() < tol
    }

    #[test]
    fn test_gp_basis() {
        let e1v = e1();
        let e2v = e2();
        let e3v = e3();
        let e0v = e0();
        let eiv = einf();
        assert!(e1v.gp(&e1v).approx_eq(&mv_scalar(1.0)));
        assert!(e2v.gp(&e2v).approx_eq(&mv_scalar(1.0)));
        assert!(e3v.gp(&e3v).approx_eq(&mv_scalar(1.0)));
        assert!(e0v.gp(&e0v).is_zero());
        assert!(eiv.gp(&eiv).is_zero());
        assert!(e0v.gp(&eiv).scalar_part() == -1.0);
        assert!(eiv.gp(&e0v).scalar_part() == -1.0);
    }

    #[test]
    fn test_null_point() {
        // conformal point p = e0 + x e1 + y e2 + z e3 + 0.5 r^2 einf is null
        let p = mv_vector(1.0, 2.0, 3.0, 1.0, 7.0);
        assert!(p.gp(&p).scalar_part() == 0.0);
        assert_eq!(p.coords(), [1.0, 2.0, 3.0]);
    }

    #[test]
    fn test_dual_involution() {
        let p = mv_vector(1.0, 2.0, 3.0, 1.0, 7.0);
        assert!(p.dual().dual().approx_eq(&p.neg()));
        assert!(p.undual().approx_eq(&p.dual().neg()));
    }

    #[test]
    fn test_reverse() {
        // reversal of a bivector flips sign
        let b = e1().op(&e2()); // e12
        assert!(b.reverse().approx_eq(&b.neg()));
        // reversal of scalar is identity
        assert!(mv_scalar(3.0).reverse().approx_eq(&mv_scalar(3.0)));
    }

    fn tb12() -> Multivector {
        e1().op(&e2())
    }

    fn tb13() -> Multivector {
        e1().op(&e3())
    }

    fn tb23() -> Multivector {
        e2().op(&e3())
    }

    #[test]
    fn test_blade_join() {
        assert!(e1().join(&e2()).approx_eq(&tb12()));
        // containment joins to the larger blade
        assert!(e1().join(&tb12()).approx_eq(&tb12()));
        // independent euclidean and conjugate blocks
        assert!(tb12()
            .join(&e0().op(&einf()))
            .approx_eq(&e1().op(&e2()).op(&e0()).op(&einf())));
        // overlapping euclidean planes join to the 3-space they span
        assert!(tb12().join(&tb23()).approx_eq(&e1().op(&e2()).op(&e3())));
        // 5D cross-grade overlap: e12 and e1e3e0 span 4 dimensions
        assert!(tb12()
            .join(&e1().op(&e3()).op(&e0()))
            .approx_eq(&e1().op(&e2()).op(&e3()).op(&e0())));
        // parallel blades share the span
        assert!(e2().join(&e2().mul_scalar(-3.0)).approx_eq(&e2()));
        // scalar / zero join as neutral
        assert!(mv_scalar(2.0).join(&e1()).approx_eq(&e1()));
        assert!(mv_zero().join(&e1()).approx_eq(&e1()));
    }

    #[test]
    fn test_blade_meet() {
        // containment cases the pure dual formula misses
        assert!(e1().meet(&tb12()).approx_eq(&e1()));
        assert!(tb12().meet(&tb12()).approx_eq(&tb12()));
        assert!(e1().meet(&mv_scalar(3.0)).approx_eq(&mv_zero()));
        // disjoint blades
        assert!(e1().meet(&e2()).approx_eq(&mv_zero()));
        assert!(e1().meet(&e0().op(&einf())).approx_eq(&mv_zero()));
        // overlapping euclidean planes meet in their common line
        assert!(tb12().meet(&tb13()).approx_eq(&e1()));
        assert!(tb12().meet(&tb23()).approx_eq(&e2()));
        // 5D cross-grade partial overlap: e12 ∩ e1e3e0 = e1
        assert!(tb12().meet(&e1().op(&e3()).op(&e0())).approx_eq(&e1()));
        // input scale does not matter
        assert!(tb12().meet(&tb13().mul_scalar(-2.0)).approx_eq(&e1()));
        // meet with the whole space: dual(dual(x)) = -x
        let mut whole = mv_zero();
        whole.values[31] = 1.0;
        assert!(whole.meet(&tb12()).approx_eq(&tb12().neg()));
    }

    #[test]
    fn test_dual_hodge() {
        // dual is now the true Hodge dual: dual(e1) = -(e2^e3^e0^einf)
        let expected = e2().op(&e3()).op(&e0()).op(&einf()).neg();
        assert!(e1().dual().approx_eq(&expected));
        // double dual inverts sign (restated for the fix)
        let p = point(1.0, 2.0, 3.0);
        assert!(p.dual().dual().approx_eq(&p.neg()));
    }

    #[test]
    fn test_blade_inverse() {
        assert!(tb12().inverse().approx_eq(&tb12().neg()));
        let v = mv_vector(1.0, 2.0, 3.0, 0.0, 0.0);
        assert!(v.gp(&v.inverse()).approx_eq(&mv_scalar(1.0)));
        let r = motor_rotor([0.0, 0.0, 1.0], 0.7);
        assert!(r.gp(&r.inverse()).approx_eq(&mv_scalar(1.0)));
        assert!(r.inverse().approx_eq(&r.reverse()));
    }

    #[test]
    fn test_blade_proj_rej() {
        let plane = tb12();
        let v = mv_vector(1.0, 2.0, 3.0, 0.0, 0.0);
        assert!(v
            .proj(&plane)
            .approx_eq(&mv_vector(1.0, 2.0, 0.0, 0.0, 0.0)));
        assert!(v.rej(&plane).approx_eq(&mv_vector(0.0, 0.0, 3.0, 0.0, 0.0)));
        assert!(v.proj(&plane).add(&v.rej(&plane)).approx_eq(&v));
        assert!(mv_vector(1.0, 2.0, 3.0, 0.0, 0.0)
            .proj(&e1())
            .approx_eq(&mv_vector(1.0, 0.0, 0.0, 0.0, 0.0)));
    }

    #[test]
    fn test_blade_reflect() {
        let v = mv_vector(1.0, 2.0, 3.0, 0.0, 0.0);
        assert!(v
            .reflect([0.0, 0.0, 1.0])
            .approx_eq(&mv_vector(1.0, 2.0, -3.0, 0.0, 0.0)));
        // the normal is normalized internally
        assert!(v
            .reflect([0.0, 0.0, 2.0])
            .approx_eq(&mv_vector(1.0, 2.0, -3.0, 0.0, 0.0)));
        assert!(e3().reflect([0.0, 0.0, 1.0]).approx_eq(&e3().neg()));
    }

    #[test]
    fn test_blade_contractions() {
        assert!(e1().lc(&tb12()).approx_eq(&e2()));
        assert!(tb12().lc(&e1()).approx_eq(&mv_zero()));
        assert!(tb12().rc(&e1()).approx_eq(&e2().neg()));
        assert!(e1().rc(&tb12()).approx_eq(&mv_zero()));
        assert!(e1().commutator(&e2()).approx_eq(&tb12()));
        assert!(e1().commutator(&e1()).approx_eq(&mv_zero()));
        assert!(e1().anticommutator(&e2()).approx_eq(&mv_zero()));
    }

    #[test]
    fn test_point_null_and_dist() {
        let p1 = point(0.0, 0.0, 0.0);
        assert!(close(p1.gp(&p1).values[0], 0.0, 1e-4));
        assert!(close(point_dist(&p1, &point(3.0, 4.0, 0.0)), 5.0, 1e-4));
    }

    #[test]
    fn test_line_incidence() {
        let l = line(&point(0.0, 0.0, 0.0), &point(1.0, 0.0, 0.0));
        assert!(close(point(2.0, 0.0, 0.0).op(&l).vmax(), 0.0, 1e-4));
        assert!(point(0.0, 1.0, 0.0).op(&l).vmax() > 1e-3);
    }

    #[test]
    fn test_plane_incidence() {
        let pi = plane([0.0, 0.0, 1.0], 2.0);
        assert!(close(point(0.3, -0.7, 2.0).ip(&pi).vmax(), 0.0, 1e-4));
        assert!(point(0.0, 0.0, 0.0).ip(&pi).vmax() > 1e-3);
    }

    #[test]
    fn test_sphere_incidence() {
        let s = sphere([1.0, 2.0, 3.0], 2.0);
        assert!(close(point(3.0, 2.0, 3.0).ip(&s).vmax(), 0.0, 1e-4));
        assert!(point(0.0, 0.0, 0.0).ip(&s).vmax() > 1e-3);
    }

    #[test]
    fn test_circle_incidence() {
        let c = circle([0.0, 0.0, 0.0], 1.0, [0.0, 0.0, 1.0]);
        assert!(close(point(0.0, 1.0, 0.0).ip(&c).vmax(), 0.0, 1e-4));
        assert!(point(0.0, 0.0, 1.0).ip(&c).vmax() > 1e-3);
        let cnu = circle([1.0, 2.0, 3.0], 2.0, [0.0, 0.0, 2.0]);
        assert!(close(point(3.0, 2.0, 3.0).ip(&cnu).vmax(), 0.0, 1e-4));
    }

    #[test]
    fn test_distances() {
        let pi = plane([0.0, 0.0, 1.0], 2.0);
        let s = sphere([1.0, 2.0, 3.0], 2.0);
        assert!(close(plane_dist(&pi, &point(0.0, 0.0, 5.0)), 3.0, 1e-4));
        assert!(close(sphere_dist(&s, &point(3.0, 2.0, 3.0)), 0.0, 1e-4));
        assert!(sphere_dist(&s, &point(5.0, 2.0, 3.0)) > 0.0);
        assert!(sphere_dist(&s, &point(1.0, 2.0, 3.0)) < 0.0);
    }

    #[test]
    fn test_meet_plane_plane() {
        let pi = plane([0.0, 0.0, 1.0], 2.0);
        let pi2 = plane([0.0, 1.0, 0.0], 1.0);
        let lm = pi.dual().meet(&pi2.dual());
        assert!(close(point(0.0, 1.0, 2.0).op(&lm).vmax(), 0.0, 1e-4));
        assert!(close(point(5.0, 1.0, 2.0).op(&lm).vmax(), 0.0, 1e-4));
    }

    #[test]
    fn test_meet_line_sphere() {
        let lz = line(&point(0.0, 0.0, -2.0), &point(0.0, 0.0, 2.0));
        let ppm = lz.meet(&sphere([0.0, 0.0, 0.0], 1.0).dual());
        assert!(close(point(0.0, 0.0, 1.0).op(&ppm).vmax(), 0.0, 1e-4));
        assert!(close(point(0.0, 0.0, -1.0).op(&ppm).vmax(), 0.0, 1e-4));
    }

    #[test]
    fn test_far_from_origin_dist() {
        assert!(close(
            point_dist(&point(1000.0, 0.0, 0.0), &point(1001.0, 0.0, 0.0)),
            1.0,
            1e-2
        ));
    }

    #[test]
    fn test_cylinder_distances() {
        let cy = cylinder([0.0, 0.0, 2.0], [0.0, 1.0, 0.0], 1.0);
        assert!(close(cylinder_dist(&cy, &point(1.0, 5.0, 2.0)), 0.0, 1e-4));
        assert!(close(cylinder_dist(&cy, &point(0.2, 0.0, 2.0)), -0.8, 1e-4));
        assert!(close(cylinder_dist(&cy, &point(3.0, -2.0, 2.0)), 2.0, 1e-4));
        assert!(close(cylinder_dist(&cy, &point(-1.0, 5.0, 2.0)), 0.0, 1e-4));
    }

    #[test]
    fn test_from_dual_after_motor() {
        let s_cam = translator([1.0, 2.0, 3.0]).apply(&sphere([0.0, 0.0, 0.0], 0.5));
        let (c, rho) = sphere_from_dual(&s_cam);
        assert!(close(c[0], 1.0, 1e-4) && close(c[1], 2.0, 1e-4) && close(c[2], 3.0, 1e-4));
        assert!(close(rho, 0.5, 1e-4));
        let pi_cam = translator([1.0, 2.0, 3.0]).apply(&plane([0.0, 1.0, 0.0], 0.0));
        assert!(close(pi_cam.einf_coeff(), 2.0, 1e-4));
    }
}
