pub mod flange_spec;
pub use self::flange_spec::*;
pub mod bolt_circle_spec;
pub use self::bolt_circle_spec::*;
pub mod gear_spec;
pub use self::gear_spec::*;
pub mod base_plate_spec;
pub use self::base_plate_spec::*;

pub fn fmt_num(x: f64) -> String {
    if x.is_finite() && x.fract() == 0.0 && x.abs() < 1e16 {
        format!("{x:.1}")
    } else {
        format!("{x}")
    }
}

fn fmt_v(v: [f64; 3]) -> String {
    format!("[{}, {}, {}]", fmt_num(v[0]), fmt_num(v[1]), fmt_num(v[2]))
}

/// JSX 场景骨架：背景/相机/灯光。子内容由各 spec 平铺填入。
pub fn gen_header(camera_pos: [f64; 3], camera_target: [f64; 3]) -> String {
    format!(
        "// generated by jsx_gen — do not hand-edit, regenerate from spec\n\
         export default (\n  <scene background={{0x2B3138}}>\n    \
         <camera fov={{45}} position={{ {} }} target={{ {} }} />\n    \
         <directional_light direction={{[0.4, 1.0, 0.5]}} intensity={{0.5}} />\n    \
         <point_light position={{[-5, 6, 4]}} intensity={{0.55}} />\n    \
         <ambient_light intensity={{0.38}} />\n",
        fmt_v(camera_pos),
        fmt_v(camera_target)
    )
}

pub fn gen_footer() -> String {
    "  </scene>\n);\n".to_string()
}

pub fn gen_post(r: f64, h: f64) -> String {
    format!(
        "<rotate axis={{[1.0, 0.0, 0.0]}} angle={{ -1.5707963267948966 }}><cylinder r={{ {} }} h={{ {} }} /></rotate>",
        fmt_num(r),
        fmt_num(h)
    )
}

/// 结构化参数 → 平铺 JSX（无组件复用、确定性、可 diff、必然可解析）。
pub fn gen_flange_assembly(
    flange: &FlangeSpec,
    bolts: &BoltCircleSpec,
    gear: &GearSpec,
    plate: &BasePlateSpec,
) -> String {
    let mut out = gen_header([7.5, 6.5, 9.5], [0.0, 1.8, 0.0]);
    out.push_str(&format!(
        "    <translate t={{[0.0, 0.15, 0.0]}}>\n{}    </translate>\n",
        plate.generate()
    ));
    out.push_str(&format!(
        "    <translate t={{[0.0, 0.55, 0.0]}}>\n{}    </translate>\n",
        flange.generate()
    ));
    out.push_str(&bolts.generate());
    out.push_str(&format!(
        "    <translate t={{[0.0, 2.9, 0.0]}}>{}</translate>\n",
        gen_post_mat(0.55, 4.2, 0x9BA1A6, 0.3, 0.8)
    ));
    out.push_str(&format!(
        "    <translate t={{[0.0, 1.25, 0.0]}}>{}</translate>\n",
        gen_post_mat(0.85, 0.9, 0x9BA1A6, 0.3, 0.8)
    ));
    out.push_str(&gear.generate());
    out.push_str(&format!(
        "    <translate t={{[0.0, 4.45, 0.0]}}><rotate axis={{[1.0, 0.0, 0.0]}} angle={{ -1.5707963267948966 }}><torus R={{0.72}} r={{0.16}} color={{0x4A4F54}} roughness={{0.45}} metalness={{0.65}} /></rotate></translate>\n\
         \x20   <translate t={{[0.0, 4.85, 0.0]}}><box s={{[0.95, 0.5, 0.95]}} color={{0x6E747A}} roughness={{0.4}} metalness={{0.7}} /></translate>\n\
         \x20   <translate t={{[0.62, 3.6, 0.0]}}><box s={{[0.18, 0.9, 0.18]}} color={{0xC8A24A}} roughness={{0.35}} metalness={{0.75}} /></translate>\n\
         \x20   <plane n={{[0.0, 1.0, 0.0]}} d={{0.0}} color={{0x3A4046}} roughness={{0.9}} />\n",
    ));
    out.push_str(&gen_footer());
    out
}

pub fn gen_post_mat(r: f64, h: f64, color: u32, roughness: f64, metalness: f64) -> String {
    format!(
        "<rotate axis={{[1.0, 0.0, 0.0]}} angle={{ -1.5707963267948966 }}><cylinder r={{ {} }} h={{ {} }} color={{0x{:06X}}} roughness={{ {} }} metalness={{ {} }} /></rotate>",
        fmt_num(r),
        fmt_num(h),
        color,
        fmt_num(roughness),
        fmt_num(metalness)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn post_golden() {
        assert_eq!(
            gen_post(2.6, 0.5),
            "<rotate axis={[1.0, 0.0, 0.0]} angle={ -1.5707963267948966 }><cylinder r={ 2.6 } h={ 0.5 } /></rotate>"
        );
    }

    #[test]
    fn flange_has_all_holes_unrolled() {
        let s = FlangeSpec::default();
        let t = s.generate();
        assert!(t.contains("<difference"));
        assert_eq!(t.matches("<cylinder").count(), 10);
        assert!(t.contains("color={0x9BA1A6}"));
    }

    #[test]
    fn generated_assembly_parses_and_counts() {
        let text = gen_flange_assembly(
            &FlangeSpec::default(),
            &BoltCircleSpec::default(),
            &GearSpec::default(),
            &BasePlateSpec::default(),
        );
        let run = crate::jsx::run_jsx(&text, None, ".").expect("generated JSX must run");
        assert_eq!(run.scene.objects.len(), 41);
    }

    #[test]
    fn gear_tooth_count() {
        let t = GearSpec::default().generate();
        assert_eq!(t.matches("<box s=").count(), 16);
    }
}
