// generated by jsx_gen — do not hand-edit, regenerate from spec
export default (
  <Scene background={0x2B3138}>
    <Camera fov={45} position={ [7.0, 5.0, 10.0] } target={ [0.0, 1.0, 0.0] } />
    <DirectionalLight direction={[0.4, 1.0, 0.5]} intensity={0.5} />
    <PointLight position={[-5, 6, 4]} intensity={0.55} />
    <AmbientLight intensity={0.38} />
    <Revolute name="revolute" axis={[0,0,1]} at={ [-4.0, 1.0, 0.0] } q={0.6}><Box s={[0.5,0.5,0.5]} color={0xC0392B} roughness={0.4} metalness={0.4} /></Revolute>
    <Gear driver="revolute" driven="prismatic" ratio={0.5} />
    <Prismatic name="prismatic" axis={[0,1,0]} at={ [-3.0, 1.0, 0.0] } limit={[-1,1]}><Box s={[0.5,0.5,0.5]} color={0xF1C40F} roughness={0.4} metalness={0.4} /></Prismatic>
    <Continuous name="continuous" axis={[0,0,1]} at={ [-2.0, 1.0, 0.0] }><Box s={[0.5,0.5,0.5]} color={0xE67E22} roughness={0.4} metalness={0.4} /></Continuous>
    <Helical name="helical" axis={[0,0,1]} at={ [-1.0, 1.0, 0.0] } pitch={0.3} q={0.5}><Box s={[0.5,0.5,0.5]} color={0x2ECC71} roughness={0.4} metalness={0.4} /></Helical>
    <Cylindrical name="cylindrical" axis={[0,0,1]} at={ [0.0, 1.0, 0.0] } q={[0.4,0.2]}><Box s={[0.5,0.5,0.5]} color={0x1ABC9C} roughness={0.4} metalness={0.4} /></Cylindrical>
    <Spherical name="spherical" at={ [1.0, 1.0, 0.0] } q={[0.2,0.3,0.1]}><Box s={[0.5,0.5,0.5]} color={0x3498DB} roughness={0.4} metalness={0.4} /></Spherical>
    <Planar name="planar" axis={[0,0,1]} at={ [2.0, 1.0, 0.0] } q={[0.2,0.1,0.3]}><Box s={[0.5,0.5,0.5]} color={0x9B59B6} roughness={0.4} metalness={0.4} /></Planar>
    <Fixed name="fixed" at={ [3.0, 1.0, 0.0] }><Box s={[0.5,0.5,0.5]} color={0x95A5A6} roughness={0.4} metalness={0.4} /></Fixed>
    <Revolute name="cam_driver" axis={[0,0,1]} at={ [0.0, 3.0, 0.0] } q={0.3}><Cylinder r={0.4} h={0.2} /></Revolute>
    <Cam driver="cam_driver" driven="cam_follower" driverProfile={{kind:"circle", c:[0.12,0,0], n:[0,0,1], r:0.4}} drivenProfile={{kind:"circle", c:[0,0,0], n:[0,0,1], r:0.12}} />
    <Prismatic name="cam_follower" axis={[1,0,0]} at={ [0.9, 3.0, 0.0] } limit={[-0.4,-0.1]}><Sphere r={0.12} /></Prismatic>
    <Plane n={[0,1,0]} d={0} color={0x3A4046} roughness={0.9} />
  </Scene>
);
